# Form implementation generated from reading ui file 'Form_Prod_venda.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(808, 500)
        MainWindow.setMinimumSize(QtCore.QSize(808, 500))
        MainWindow.setMaximumSize(QtCore.QSize(808, 500))
        MainWindow.setMouseTracking(False)
        MainWindow.setAcceptDrops(False)
        MainWindow.setWindowTitle("")
        MainWindow.setToolTip("")
        MainWindow.setStatusTip("")
        MainWindow.setWhatsThis("")
        MainWindow.setWindowFilePath("")
        MainWindow.setAnimated(False)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(808, 500))
        self.centralwidget.setMaximumSize(QtCore.QSize(808, 500))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.TableWidget_Produto = QtWidgets.QTableWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TableWidget_Produto.sizePolicy().hasHeightForWidth())
        self.TableWidget_Produto.setSizePolicy(sizePolicy)
        self.TableWidget_Produto.setMinimumSize(QtCore.QSize(808, 0))
        self.TableWidget_Produto.setMaximumSize(QtCore.QSize(808, 16777215))
        self.TableWidget_Produto.setStyleSheet("QHeaderView:section{\n"
"background-color: rgb(255, 255, 255);\n"
"padding: 5px 5px 5px 0px ;\n"
"font-size: 9px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: rgb(136, 136, 136);\n"
"border:none;\n"
"border-bottom: 1px solid #CCC;\n"
"}\n"
"QTableView{\n"
"background-color: rgb(255, 255, 255);\n"
"font-size: 12px;\n"
"color: rgb(113, 113, 113);\n"
"\n"
"}\n"
"")
        self.TableWidget_Produto.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.TableWidget_Produto.setAlternatingRowColors(False)
        self.TableWidget_Produto.setShowGrid(True)
        self.TableWidget_Produto.setObjectName("TableWidget_Produto")
        self.TableWidget_Produto.setColumnCount(7)
        self.TableWidget_Produto.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Produto.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Produto.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Produto.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Produto.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Produto.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Produto.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Produto.setHorizontalHeaderItem(6, item)
        self.TableWidget_Produto.horizontalHeader().setCascadingSectionResizes(False)
        self.TableWidget_Produto.horizontalHeader().setDefaultSectionSize(126)
        self.TableWidget_Produto.verticalHeader().setCascadingSectionResizes(False)
        self.gridLayout.addWidget(self.TableWidget_Produto, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.TableWidget_Produto.setSortingEnabled(False)
        item = self.TableWidget_Produto.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.TableWidget_Produto.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "CÓDIGO"))
        item = self.TableWidget_Produto.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "DESCRIÇÃO"))
        item = self.TableWidget_Produto.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "PREÇO"))
        item = self.TableWidget_Produto.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "ESTOQUE"))
        item = self.TableWidget_Produto.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "CATEGORIA"))
        item = self.TableWidget_Produto.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "MARCA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
