# Form implementation generated from reading ui file 'Form_Inicio.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QFrame


class Ui_Form_Inicio(object):
    def setupUi(self, Form_Inicio):
        Form_Inicio.setObjectName("Form_Inicio")
        Form_Inicio.resize(1274, 816)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/sistemablue.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form_Inicio.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=Form_Inicio)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_35.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_35.setSpacing(0)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.frame_lateral = QtWidgets.QFrame(parent=self.frame)
        self.frame_lateral.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_lateral.setMaximumSize(QtCore.QSize(0, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.frame_lateral.setFont(font)
        self.frame_lateral.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.518552, y1:0.414227, x2:0.52957, y2:1, stop:0 #000046 , stop:1 #1CB5E0);\n"
"")
        self.frame_lateral.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_lateral.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_lateral.setObjectName("frame_lateral")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_lateral)
        self.verticalLayout_13.setContentsMargins(5, 5, 5, 0)
        self.verticalLayout_13.setSpacing(15)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.Bt_Add_frame = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.Bt_Add_frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.Bt_Add_frame.setObjectName("Bt_Add_frame")
        self.verticalLayout_13.addWidget(self.Bt_Add_frame)
        spacerItem = QtWidgets.QSpacerItem(20, 221, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_13.addItem(spacerItem)
        self.label_23 = QtWidgets.QLabel(parent=self.frame_lateral)
        self.label_23.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:1CB5E0;")
        self.label_23.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_13.addWidget(self.label_23)
        self.gridLayout_35.addWidget(self.frame_lateral, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setStyleSheet("background-color: rgb(118, 118, 118);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Mesa = QtWidgets.QWidget()
        self.Mesa.setObjectName("Mesa")
        self.gridLayout_41 = QtWidgets.QGridLayout(self.Mesa)
        self.gridLayout_41.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_41.setSpacing(0)
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.frame_70 = QtWidgets.QFrame(parent=self.Mesa)
        self.frame_70.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.frame_70.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_70.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_70.setObjectName("frame_70")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_70)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_71 = QtWidgets.QFrame(parent=self.frame_70)
        self.frame_71.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_71.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.frame_71.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_71.setObjectName("frame_71")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_71)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.frame_104 = QtWidgets.QFrame(parent=self.frame_71)
        self.frame_104.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_104.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_104.setObjectName("frame_104")
        self.gridLayout_58 = QtWidgets.QGridLayout(self.frame_104)
        self.gridLayout_58.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_58.setVerticalSpacing(0)
        self.gridLayout_58.setObjectName("gridLayout_58")
        self.label_50 = QtWidgets.QLabel(parent=self.frame_104)
        self.label_50.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_50.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_50.setObjectName("label_50")
        self.gridLayout_58.addWidget(self.label_50, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_104)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton.setStyleSheet("border:none;")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/Garcon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(45, 45))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_58.addWidget(self.pushButton, 0, 0, 1, 1)
        self.horizontalLayout_18.addWidget(self.frame_104)
        self.frame_103 = QtWidgets.QFrame(parent=self.frame_71)
        self.frame_103.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_103.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_103.setObjectName("frame_103")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_103)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_90 = QtWidgets.QLabel(parent=self.frame_103)
        self.label_90.setMaximumSize(QtCore.QSize(175, 16777215))
        self.label_90.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_90.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_90.setObjectName("label_90")
        self.horizontalLayout_19.addWidget(self.label_90)
        self.Lb_Nome_Empresa = QtWidgets.QLabel(parent=self.frame_103)
        self.Lb_Nome_Empresa.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.Lb_Nome_Empresa.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.Lb_Nome_Empresa.setObjectName("Lb_Nome_Empresa")
        self.horizontalLayout_19.addWidget(self.Lb_Nome_Empresa)
        self.horizontalLayout_18.addWidget(self.frame_103)
        self.verticalLayout_15.addWidget(self.frame_71)
        self.frame_72 = QtWidgets.QFrame(parent=self.frame_70)
        self.frame_72.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_72.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_72.setObjectName("frame_72")
        self.gridLayout_47 = QtWidgets.QGridLayout(self.frame_72)
        self.gridLayout_47.setObjectName("gridLayout_47")
        self.Frame_Mesa01 = QtWidgets.QFrame(parent=self.frame_72)
        self.Frame_Mesa01.setMaximumSize(QtCore.QSize(196, 146))
        self.Frame_Mesa01.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Frame_Mesa01.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.Frame_Mesa01.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Frame_Mesa01.setObjectName("Frame_Mesa01")
        self.gridLayout_42 = QtWidgets.QGridLayout(self.Frame_Mesa01)
        self.gridLayout_42.setObjectName("gridLayout_42")
        self.Lb_Status_Mesa01 = QtWidgets.QLabel(parent=self.Frame_Mesa01)
        self.Lb_Status_Mesa01.setStyleSheet("color: rgb(0, 170, 127);\n"
"\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.Lb_Status_Mesa01.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Lb_Status_Mesa01.setObjectName("Lb_Status_Mesa01")
        self.gridLayout_42.addWidget(self.Lb_Status_Mesa01, 1, 0, 1, 1)
        self.Bt_Mesa01 = QtWidgets.QPushButton(parent=self.Frame_Mesa01)
        self.Bt_Mesa01.setMaximumSize(QtCore.QSize(85, 16777215))
        self.Bt_Mesa01.setStyleSheet("background-color: rgb(162, 162, 162);\n"
"color: rgb(0, 0, 255);")
        self.Bt_Mesa01.setObjectName("Bt_Mesa01")
        self.gridLayout_42.addWidget(self.Bt_Mesa01, 2, 0, 1, 1)
        self.Lb_Mesa01 = QtWidgets.QLabel(parent=self.Frame_Mesa01)
        self.Lb_Mesa01.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.Lb_Mesa01.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Lb_Mesa01.setObjectName("Lb_Mesa01")
        self.gridLayout_42.addWidget(self.Lb_Mesa01, 0, 0, 1, 1)
        self.gridLayout_47.addWidget(self.Frame_Mesa01, 0, 0, 1, 1)
        self.verticalLayout_15.addWidget(self.frame_72)
        self.gridLayout_41.addWidget(self.frame_70, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.Mesa)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.gridLayout_35.addWidget(self.frame_3, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        Form_Inicio.setCentralWidget(self.centralwidget)

        self.retranslateUi(Form_Inicio)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form_Inicio)

    def retranslateUi(self, Form_Inicio):
        _translate = QtCore.QCoreApplication.translate
        Form_Inicio.setWindowTitle(_translate("Form_Inicio", "LC SISTEMAS"))
        self.Bt_Add_frame.setText(_translate("Form_Inicio", "Add"))
        self.label_23.setText(_translate("Form_Inicio", "Versão 1.0.0"))
        self.label_50.setText(_translate("Form_Inicio", "PEDIDOS PARA MESAS"))
        self.label_90.setText(_translate("Form_Inicio", "Nome da Empresa:"))
        self.Lb_Nome_Empresa.setText(_translate("Form_Inicio", "LC INFORMÁTICA"))
        self.Lb_Status_Mesa01.setText(_translate("Form_Inicio", "Livre"))
        self.Bt_Mesa01.setText(_translate("Form_Inicio", "Detalhes"))
        self.Lb_Mesa01.setText(_translate("Form_Inicio", "Mesa - 01"))
        self.Bt_Add_frame.clicked.connect(self.add_child_frame)
        
        self.child_count = 0
    def add_child_frame(self):
        self.child_frame = QtWidgets.QFrame(parent=self.frame_72)
        self.child_frame.setFixedSize(196, 146)  
        self.child_frame.setStyleSheet("""background-color: rgb(255, 255, 255);
        border-radius:15px;""")
        self.child_frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        row = self.child_count // 5  
        col = self.child_count % 5

        # Adding child_frame to gridLayout_47
        self.gridLayout_47.addWidget(self.child_frame, row + 1, col)

        # Adding labels to the top of the child_frame
        label1 = QtWidgets.QLabel("Mesa - 01")
        label2 = QtWidgets.QLabel("Livre")

        top_layout = QtWidgets.QHBoxLayout()
        top_layout.addWidget(label1)
        top_layout.addWidget(label2)

        self.child_frame.setLayout(top_layout)  # Set the layout for the child_frame

        self.child_count += 1





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_Inicio = QtWidgets.QMainWindow()
    ui = Ui_Form_Inicio()
    ui.setupUi(Form_Inicio)
    Form_Inicio.show()
    sys.exit(app.exec())
