# Form implementation generated from reading ui file 'Form_Finaliza_Venda.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Fecha_Venda(object):
    def setupUi(self, Fecha_Venda):
        Fecha_Venda.setObjectName("Fecha_Venda")
        Fecha_Venda.resize(500, 590)
        Fecha_Venda.setMinimumSize(QtCore.QSize(500, 590))
        Fecha_Venda.setMaximumSize(QtCore.QSize(500, 590))
        Fecha_Venda.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=Fecha_Venda)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame_6)
        self.label.setStyleSheet("font: 15pt \"Rockwell\";")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_8)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_11.setStyleSheet("font: 30pt \"Rockwell\";")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.Lb_TotalPagar = QtWidgets.QLabel(parent=self.frame_7)
        self.Lb_TotalPagar.setMinimumSize(QtCore.QSize(150, 0))
        self.Lb_TotalPagar.setStyleSheet("border-radius: 2px;\n"
"font: 30pt \"Rockwell\";\n"
"\n"
"")
        self.Lb_TotalPagar.setObjectName("Lb_TotalPagar")
        self.horizontalLayout_2.addWidget(self.Lb_TotalPagar)
        self.gridLayout_2.addWidget(self.frame_7, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_8)
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setStyleSheet("color: rgb(152, 152, 152);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-bottom:1px solid #9d9d9d;\n"
"\n"
"\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_5.setStyleSheet("font: 15pt \"Rockwell\";\n"
"border: none;\n"
"font: 15pt \"Rockwell\";\n"
"color: rgb(0, 129, 194);")
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.Cb_FormaPagamento = QtWidgets.QComboBox(parent=self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Cb_FormaPagamento.sizePolicy().hasHeightForWidth())
        self.Cb_FormaPagamento.setSizePolicy(sizePolicy)
        self.Cb_FormaPagamento.setMinimumSize(QtCore.QSize(0, 50))
        self.Cb_FormaPagamento.setStyleSheet("QComboBox{\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 238);\n"
"border-radius: 2px;\n"
"border:none;\n"
"font: 25px \"Arial\" ;\n"
"\n"
"}\n"
"QComboBox:Focus {\n"
"border: 1px solid red;\n"
"color: rgb(0, 0, 0);\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"font: 25px \"Arial\" ;\n"
"}")
        self.Cb_FormaPagamento.setObjectName("Cb_FormaPagamento")
        self.Cb_FormaPagamento.addItem("")
        self.Cb_FormaPagamento.addItem("")
        self.Cb_FormaPagamento.addItem("")
        self.Cb_FormaPagamento.addItem("")
        self.Cb_FormaPagamento.addItem("")
        self.gridLayout_5.addWidget(self.Cb_FormaPagamento, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_10.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-bottom:1px solid #9d9d9d;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_3.setStyleSheet("font: 15pt \"Rockwell\";\n"
"border:none;\n"
"color: rgb(0, 129, 194);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 0, 0, 1, 1)
        self.Input_ValorPago = QtWidgets.QLineEdit(parent=self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Input_ValorPago.sizePolicy().hasHeightForWidth())
        self.Input_ValorPago.setSizePolicy(sizePolicy)
        self.Input_ValorPago.setMinimumSize(QtCore.QSize(150, 0))
        self.Input_ValorPago.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Input_ValorPago.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.Input_ValorPago.setAutoFillBackground(False)
        self.Input_ValorPago.setStyleSheet("QLineEdit{\n"
"background-color: rgb(238, 238, 238);\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 25px \"Arial\" ;\n"
"border:none;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.Input_ValorPago.setInputMask("")
        self.Input_ValorPago.setText("00,00")
        self.Input_ValorPago.setFrame(False)
        self.Input_ValorPago.setCursorPosition(5)
        self.Input_ValorPago.setClearButtonEnabled(False)
        self.Input_ValorPago.setObjectName("Input_ValorPago")
        self.gridLayout_6.addWidget(self.Input_ValorPago, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_10.setStyleSheet("font: 30pt \"Rockwell\";\n"
"border:none;")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-bottom:1px solid #9d9d9d;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_7.setStyleSheet("font:30pt \"Rockwell\";\n"
"border:none;")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 1, 1, 1, 1)
        self.Lb_Troco = QtWidgets.QLabel(parent=self.frame_11)
        self.Lb_Troco.setMinimumSize(QtCore.QSize(0, 50))
        self.Lb_Troco.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Lb_Troco.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"border-radius: 2px;\n"
"font: 25px \"Arial\" ;\n"
"border:none;")
        self.Lb_Troco.setObjectName("Lb_Troco")
        self.gridLayout_7.addWidget(self.Lb_Troco, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_6.setStyleSheet("font: 15pt \"Rockwell\";\n"
"border:none;\n"
"color: rgb(0, 129, 194);")
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_11)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_14 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_16 = QtWidgets.QFrame(parent=self.frame_14)
        self.frame_16.setStyleSheet("color: rgb(147, 147, 147);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.Bt_check = QtWidgets.QCheckBox(parent=self.frame_16)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.Bt_check.setFont(font)
        self.Bt_check.setStyleSheet("\n"
"QCheckBox{border:none;}\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(100, 100, 100);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;    \n"
"    \n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 205, 0);\n"
"}\n"
"")
        self.Bt_check.setObjectName("Bt_check")
        self.gridLayout_8.addWidget(self.Bt_check, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_16, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_14)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Bt_Confirmar_Vanda = QtWidgets.QPushButton(parent=self.frame_5)
        self.Bt_Confirmar_Vanda.setMinimumSize(QtCore.QSize(0, 35))
        self.Bt_Confirmar_Vanda.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 45px;\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.Bt_Confirmar_Vanda.setObjectName("Bt_Confirmar_Vanda")
        self.gridLayout_4.addWidget(self.Bt_Confirmar_Vanda, 0, 1, 1, 1)
        self.Bt_Cancelar_Venda = QtWidgets.QPushButton(parent=self.frame_5)
        self.Bt_Cancelar_Venda.setMinimumSize(QtCore.QSize(0, 35))
        self.Bt_Cancelar_Venda.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 45px;\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.Bt_Cancelar_Venda.setObjectName("Bt_Cancelar_Venda")
        self.gridLayout_4.addWidget(self.Bt_Cancelar_Venda, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_5)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        Fecha_Venda.setCentralWidget(self.centralwidget)

        self.retranslateUi(Fecha_Venda)
        QtCore.QMetaObject.connectSlotsByName(Fecha_Venda)

    def retranslateUi(self, Fecha_Venda):
        _translate = QtCore.QCoreApplication.translate
        Fecha_Venda.setWindowTitle(_translate("Fecha_Venda", "MainWindow"))
        self.label.setText(_translate("Fecha_Venda", "Total a pagar"))
        self.label_11.setText(_translate("Fecha_Venda", "R$"))
        self.Lb_TotalPagar.setText(_translate("Fecha_Venda", "0,00"))
        self.label_2.setText(_translate("Fecha_Venda", "F3 DESCONTO"))
        self.label_5.setText(_translate("Fecha_Venda", "Forma de Pagamento"))
        self.Cb_FormaPagamento.setItemText(0, _translate("Fecha_Venda", "Dinheiro"))
        self.Cb_FormaPagamento.setItemText(1, _translate("Fecha_Venda", "Cartão"))
        self.Cb_FormaPagamento.setItemText(2, _translate("Fecha_Venda", "Pix"))
        self.Cb_FormaPagamento.setItemText(3, _translate("Fecha_Venda", "Cheque"))
        self.Cb_FormaPagamento.setItemText(4, _translate("Fecha_Venda", "Nota"))
        self.label_3.setText(_translate("Fecha_Venda", "Valor Pago"))
        self.label_10.setText(_translate("Fecha_Venda", "R$"))
        self.label_7.setText(_translate("Fecha_Venda", "R$"))
        self.Lb_Troco.setText(_translate("Fecha_Venda", "0,00"))
        self.label_6.setText(_translate("Fecha_Venda", "Troco"))
        self.Bt_check.setToolTip(_translate("Fecha_Venda", "Clique aqui para visualizar e ocultar a senha"))
        self.Bt_check.setText(_translate("Fecha_Venda", "Visualizar"))
        self.Bt_Confirmar_Vanda.setText(_translate("Fecha_Venda", "Confirmar Venda"))
        self.Bt_Cancelar_Venda.setText(_translate("Fecha_Venda", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Fecha_Venda = QtWidgets.QMainWindow()
    ui = Ui_Fecha_Venda()
    ui.setupUi(Fecha_Venda)
    Fecha_Venda.show()
    sys.exit(app.exec())
