# Form implementation generated from reading ui file 'Form_Cad_Usuario.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_Cad_Usuario(object):
    def setupUi(self, Form_Cad_Usuario):
        Form_Cad_Usuario.setObjectName("Form_Cad_Usuario")
        Form_Cad_Usuario.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Form_Cad_Usuario.resize(800, 470)
        Form_Cad_Usuario.setMinimumSize(QtCore.QSize(800, 470))
        Form_Cad_Usuario.setMaximumSize(QtCore.QSize(800, 470))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../img/adduser_.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form_Cad_Usuario.setWindowIcon(icon)
        self.fr_FormProdutos = QtWidgets.QFrame(parent=Form_Cad_Usuario)
        self.fr_FormProdutos.setGeometry(QtCore.QRect(0, -1, 1000, 531))
        self.fr_FormProdutos.setStyleSheet("background: #FFF;\n"
"border: none")
        self.fr_FormProdutos.setObjectName("fr_FormProdutos")
        self.lb_FormProdutos = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos.setGeometry(QtCore.QRect(19, 10, 961, 30))
        self.lb_FormProdutos.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"\n"
"border-bottom: 2px solid #A2A2A2\n"
"}")
        self.lb_FormProdutos.setObjectName("lb_FormProdutos")
        self.tx_idProduto = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_idProduto.setEnabled(False)
        self.tx_idProduto.setGeometry(QtCore.QRect(20, 170, 150, 25))
        self.tx_idProduto.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border: 1px solid #A2A2A2;\n"
"color: #000;\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"\n"
"}")
        self.tx_idProduto.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_idProduto.setObjectName("tx_idProduto")
        self.lb_FotoProduto = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FotoProduto.setGeometry(QtCore.QRect(20, 70, 241, 271))
        self.lb_FotoProduto.setStyleSheet("border: 1px solid #A2A2A2;\n"
"\n"
"")
        self.lb_FotoProduto.setText("")
        self.lb_FotoProduto.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_FotoProduto.setObjectName("lb_FotoProduto")
        self.lb_FormProdutos_2 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_2.setGeometry(QtCore.QRect(280, 60, 150, 20))
        self.lb_FormProdutos_2.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_2.setObjectName("lb_FormProdutos_2")
        self.tx_nome = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_nome.setGeometry(QtCore.QRect(280, 85, 450, 25))
        self.tx_nome.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_nome.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase;\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_nome.setObjectName("tx_nome")
        self.lb_FormProdutos_3 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_3.setGeometry(QtCore.QRect(280, 290, 111, 20))
        self.lb_FormProdutos_3.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_3.setObjectName("lb_FormProdutos_3")
        self.cb_Nivel_Acesso = QtWidgets.QComboBox(parent=self.fr_FormProdutos)
        self.cb_Nivel_Acesso.setGeometry(QtCore.QRect(280, 320, 221, 25))
        self.cb_Nivel_Acesso.setStyleSheet("QComboBox{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase\n"
"}\n"
"QComboBox:Focus {\n"
"border: 1px solid red;\n"
"}\n"
" QComboBox::drop-down {\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 25px;\n"
"     border-left-width: 1px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"QComboBox::down-arrow {\n"
"     image: url(\"+self.resourcepath(\'Images/down.png\')+\");\n"
" }\n"
"")
        self.cb_Nivel_Acesso.setObjectName("cb_Nivel_Acesso")
        self.cb_Nivel_Acesso.addItem("")
        self.cb_Nivel_Acesso.addItem("")
        self.cb_Nivel_Acesso.addItem("")
        self.lb_FormProdutos_4 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_4.setGeometry(QtCore.QRect(580, 290, 81, 20))
        self.lb_FormProdutos_4.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_4.setObjectName("lb_FormProdutos_4")
        self.cb_Permissoes = QtWidgets.QComboBox(parent=self.fr_FormProdutos)
        self.cb_Permissoes.setGeometry(QtCore.QRect(520, 320, 211, 25))
        self.cb_Permissoes.setStyleSheet("QComboBox{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase\n"
"}\n"
"QComboBox:Focus {\n"
"border: 1px solid red;\n"
"}\n"
" QComboBox::drop-down {\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 25px;\n"
"     border-left-width: 1px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"QComboBox::down-arrow {\n"
"     image: url(\"+self.resourcepath(\'Images/down.png\')+\");\n"
" }\n"
"")
        self.cb_Permissoes.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertAtBottom)
        self.cb_Permissoes.setFrame(False)
        self.cb_Permissoes.setObjectName("cb_Permissoes")
        self.cb_Permissoes.addItem("")
        self.cb_Permissoes.addItem("")
        self.cb_Permissoes.addItem("")
        self.cb_Permissoes.addItem("")
        self.lb_FormProdutos_8 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_8.setGeometry(QtCore.QRect(20, 350, 960, 30))
        self.lb_FormProdutos_8.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: normal;\n"
"\n"
"border-bottom: 2px solid #A2A2A2;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_8.setText("")
        self.lb_FormProdutos_8.setObjectName("lb_FormProdutos_8")
        self.fr_BotoesFormProdutos = QtWidgets.QFrame(parent=self.fr_FormProdutos)
        self.fr_BotoesFormProdutos.setGeometry(QtCore.QRect(0, 470, 1000, 30))
        self.fr_BotoesFormProdutos.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: none;")
        self.fr_BotoesFormProdutos.setObjectName("fr_BotoesFormProdutos")
        self.lb_FormProdutos_5 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_5.setGeometry(QtCore.QRect(280, 130, 150, 20))
        self.lb_FormProdutos_5.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_5.setObjectName("lb_FormProdutos_5")
        self.tx_Login = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_Login.setGeometry(QtCore.QRect(280, 160, 450, 25))
        self.tx_Login.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Login.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase;\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Login.setObjectName("tx_Login")
        self.lb_FormProdutos_6 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_6.setGeometry(QtCore.QRect(280, 210, 150, 20))
        self.lb_FormProdutos_6.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_6.setObjectName("lb_FormProdutos_6")
        self.tx_Senha = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_Senha.setGeometry(QtCore.QRect(280, 240, 221, 25))
        self.tx_Senha.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Senha.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase;\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Senha.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.tx_Senha.setObjectName("tx_Senha")
        self.lb_FormProdutos_9 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_9.setGeometry(QtCore.QRect(570, 210, 150, 20))
        self.lb_FormProdutos_9.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_9.setObjectName("lb_FormProdutos_9")
        self.tx_Senha2 = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_Senha2.setGeometry(QtCore.QRect(520, 240, 211, 25))
        self.tx_Senha2.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Senha2.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase;\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Senha2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.tx_Senha2.setObjectName("tx_Senha2")
        self.Bt_Add_Foto = QtWidgets.QPushButton(parent=self.fr_FormProdutos)
        self.Bt_Add_Foto.setGeometry(QtCore.QRect(40, 170, 191, 51))
        self.Bt_Add_Foto.setObjectName("Bt_Add_Foto")
        self.bt_SalvarUsuario = QtWidgets.QPushButton(parent=self.fr_FormProdutos)
        self.bt_SalvarUsuario.setGeometry(QtCore.QRect(510, 440, 91, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_SalvarUsuario.setFont(font)
        self.bt_SalvarUsuario.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_SalvarUsuario.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.bt_SalvarUsuario.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.bt_SalvarUsuario.setStyleSheet("QPushButton {\n"
"background-color: #7AB32E;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/salvar/salvar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_SalvarUsuario.setIcon(icon1)
        self.bt_SalvarUsuario.setIconSize(QtCore.QSize(50, 25))
        self.bt_SalvarUsuario.setObjectName("bt_SalvarUsuario")
        self.Bt_CancelarUsuario = QtWidgets.QPushButton(parent=self.fr_FormProdutos)
        self.Bt_CancelarUsuario.setGeometry(QtCore.QRect(630, 440, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Bt_CancelarUsuario.setFont(font)
        self.Bt_CancelarUsuario.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Bt_CancelarUsuario.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.Bt_CancelarUsuario.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.Bt_CancelarUsuario.setStyleSheet("QPushButton {\n"
"background-color: #1E87F0;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/sair/delete_delete_exit_1577.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_CancelarUsuario.setIcon(icon2)
        self.Bt_CancelarUsuario.setIconSize(QtCore.QSize(75, 25))
        self.Bt_CancelarUsuario.setObjectName("Bt_CancelarUsuario")
        self.label = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.label.setGeometry(QtCore.QRect(470, 320, 31, 25))
        self.label.setStyleSheet("QLabel{\n"
"background: #7AB32E;\n"
"color: #FFF\n"
"}\n"
"QLabel:hover{\n"
"background-color: #40a286\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.label_2.setGeometry(QtCore.QRect(700, 320, 31, 25))
        self.label_2.setStyleSheet("QLabel{\n"
"background: #7AB32E;\n"
"color: #FFF\n"
"}\n"
"QLabel:hover{\n"
"background-color: #40a286\n"
"}")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form_Cad_Usuario)
        QtCore.QMetaObject.connectSlotsByName(Form_Cad_Usuario)
        Form_Cad_Usuario.setTabOrder(self.tx_nome, self.tx_Login)
        Form_Cad_Usuario.setTabOrder(self.tx_Login, self.tx_Senha)
        Form_Cad_Usuario.setTabOrder(self.tx_Senha, self.tx_Senha2)
        Form_Cad_Usuario.setTabOrder(self.tx_Senha2, self.cb_Nivel_Acesso)
        Form_Cad_Usuario.setTabOrder(self.cb_Nivel_Acesso, self.cb_Permissoes)
        Form_Cad_Usuario.setTabOrder(self.cb_Permissoes, self.Bt_Add_Foto)
        Form_Cad_Usuario.setTabOrder(self.Bt_Add_Foto, self.tx_idProduto)

    def retranslateUi(self, Form_Cad_Usuario):
        _translate = QtCore.QCoreApplication.translate
        Form_Cad_Usuario.setWindowTitle(_translate("Form_Cad_Usuario", "LC INFORMÁTICA | CADASTRO USUÁRIOS"))
        self.lb_FormProdutos.setText(_translate("Form_Cad_Usuario", "CADASTRO USUÁRIO"))
        self.tx_idProduto.setText(_translate("Form_Cad_Usuario", "selecione uma foto"))
        self.lb_FormProdutos_2.setText(_translate("Form_Cad_Usuario", "NOME COMPLETO"))
        self.tx_nome.setPlaceholderText(_translate("Form_Cad_Usuario", "DIGITE SEU NOME"))
        self.lb_FormProdutos_3.setText(_translate("Form_Cad_Usuario", "NÍVEL DE ACESSO"))
        self.cb_Nivel_Acesso.setItemText(0, _translate("Form_Cad_Usuario", "SELECIONE"))
        self.cb_Nivel_Acesso.setItemText(1, _translate("Form_Cad_Usuario", "ADMINISTRADOR"))
        self.cb_Nivel_Acesso.setItemText(2, _translate("Form_Cad_Usuario", "USUÁRIO"))
        self.lb_FormProdutos_4.setText(_translate("Form_Cad_Usuario", "PERMISSÕES"))
        self.cb_Permissoes.setItemText(0, _translate("Form_Cad_Usuario", "SELECIONE"))
        self.cb_Permissoes.setItemText(1, _translate("Form_Cad_Usuario", "TODAS"))
        self.cb_Permissoes.setItemText(2, _translate("Form_Cad_Usuario", "ALTERAR"))
        self.cb_Permissoes.setItemText(3, _translate("Form_Cad_Usuario", "VISUALIZAR"))
        self.lb_FormProdutos_5.setText(_translate("Form_Cad_Usuario", "NOME DE USUÁRIO"))
        self.tx_Login.setPlaceholderText(_translate("Form_Cad_Usuario", "DIGiTE SEU LOGIN"))
        self.lb_FormProdutos_6.setText(_translate("Form_Cad_Usuario", "SENHA"))
        self.tx_Senha.setPlaceholderText(_translate("Form_Cad_Usuario", "DIGITE SUA SENHA"))
        self.lb_FormProdutos_9.setText(_translate("Form_Cad_Usuario", "REPITA A SENHA"))
        self.tx_Senha2.setPlaceholderText(_translate("Form_Cad_Usuario", "DIGITE A SENHA NOVAMENTE"))
        self.Bt_Add_Foto.setText(_translate("Form_Cad_Usuario", "Selecione uma foto"))
        self.bt_SalvarUsuario.setText(_translate("Form_Cad_Usuario", "SALVAR"))
        self.Bt_CancelarUsuario.setText(_translate("Form_Cad_Usuario", "CANCELAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_Cad_Usuario = QtWidgets.QFrame()
    ui = Ui_Form_Cad_Usuario()
    ui.setupUi(Form_Cad_Usuario)
    Form_Cad_Usuario.show()
    sys.exit(app.exec())
