# Form implementation generated from reading ui file 'Form_Chama_Venda.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Chama_Venda(object):
    def setupUi(self, Chama_Venda):
        Chama_Venda.setObjectName("Chama_Venda")
        Chama_Venda.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Chama_Venda.resize(800, 327)
        Chama_Venda.setMinimumSize(QtCore.QSize(800, 327))
        Chama_Venda.setMaximumSize(QtCore.QSize(800, 327))
        Chama_Venda.setToolTip("")
        Chama_Venda.setAutoFillBackground(True)
        Chama_Venda.setWindowFilePath("")
        Chama_Venda.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        Chama_Venda.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(parent=Chama_Venda)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(800, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setStyleSheet("background-color: rgb(0, 85, 127);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Bt_Venda_Balcao = QtWidgets.QPushButton(parent=self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bt_Venda_Balcao.sizePolicy().hasHeightForWidth())
        self.Bt_Venda_Balcao.setSizePolicy(sizePolicy)
        self.Bt_Venda_Balcao.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 85, 127);\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 91, 134);\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"\n"
"text-decoration: underline;\n"
"color: rgb(255, 255, 255);}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/VENDABAOCAO.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_Venda_Balcao.setIcon(icon)
        self.Bt_Venda_Balcao.setIconSize(QtCore.QSize(65, 65))
        self.Bt_Venda_Balcao.setObjectName("Bt_Venda_Balcao")
        self.gridLayout_3.addWidget(self.Bt_Venda_Balcao, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_5)
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Bt_Venda_Mesa = QtWidgets.QPushButton(parent=self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bt_Venda_Mesa.sizePolicy().hasHeightForWidth())
        self.Bt_Venda_Mesa.setSizePolicy(sizePolicy)
        self.Bt_Venda_Mesa.setMouseTracking(False)
        self.Bt_Venda_Mesa.setTabletTracking(False)
        self.Bt_Venda_Mesa.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.Bt_Venda_Mesa.setAutoFillBackground(False)
        self.Bt_Venda_Mesa.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 85, 127);\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 91, 134);\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"\n"
"text-decoration: underline;\n"
"color: rgb(255, 255, 255);}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/Garcon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_Venda_Mesa.setIcon(icon1)
        self.Bt_Venda_Mesa.setIconSize(QtCore.QSize(65, 65))
        self.Bt_Venda_Mesa.setShortcut("")
        self.Bt_Venda_Mesa.setAutoRepeat(False)
        self.Bt_Venda_Mesa.setAutoExclusive(False)
        self.Bt_Venda_Mesa.setAutoDefault(False)
        self.Bt_Venda_Mesa.setDefault(False)
        self.Bt_Venda_Mesa.setFlat(False)
        self.Bt_Venda_Mesa.setObjectName("Bt_Venda_Mesa")
        self.gridLayout_4.addWidget(self.Bt_Venda_Mesa, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_7)
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Bt_Venda_Delivery = QtWidgets.QPushButton(parent=self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bt_Venda_Delivery.sizePolicy().hasHeightForWidth())
        self.Bt_Venda_Delivery.setSizePolicy(sizePolicy)
        self.Bt_Venda_Delivery.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 85, 127);\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 91, 134);\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"\n"
"text-decoration: underline;\n"
"color: rgb(255, 255, 255);}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/DELIVERY.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_Venda_Delivery.setIcon(icon2)
        self.Bt_Venda_Delivery.setIconSize(QtCore.QSize(65, 65))
        self.Bt_Venda_Delivery.setObjectName("Bt_Venda_Delivery")
        self.gridLayout_5.addWidget(self.Bt_Venda_Delivery, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_6)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setStyleSheet("background-color: rgb(0, 85, 127);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.Bt_Voltar = QtWidgets.QPushButton(parent=self.frame_3)
        self.Bt_Voltar.setMinimumSize(QtCore.QSize(0, 45))
        self.Bt_Voltar.setMaximumSize(QtCore.QSize(250, 16777215))
        self.Bt_Voltar.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 170, 255);\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 170, 255);\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n"
"color: rgb(255, 255, 255);}")
        self.Bt_Voltar.setObjectName("Bt_Voltar")
        self.gridLayout_6.addWidget(self.Bt_Voltar, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_3)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        Chama_Venda.setCentralWidget(self.centralwidget)

        self.retranslateUi(Chama_Venda)
        QtCore.QMetaObject.connectSlotsByName(Chama_Venda)

    def retranslateUi(self, Chama_Venda):
        _translate = QtCore.QCoreApplication.translate
        Chama_Venda.setWindowTitle(_translate("Chama_Venda", "SELECIONAR VENDA"))
        self.label.setText(_translate("Chama_Venda", "SELECIONAR PARA ONDE VAI O PEDIDO"))
        self.Bt_Venda_Balcao.setText(_translate("Chama_Venda", "VENDA BALCÃO"))
        self.Bt_Venda_Mesa.setText(_translate("Chama_Venda", "VENDA MESA"))
        self.Bt_Venda_Delivery.setText(_translate("Chama_Venda", "VENDA DELIVERY"))
        self.Bt_Voltar.setText(_translate("Chama_Venda", "VOLTAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Chama_Venda = QtWidgets.QMainWindow()
    ui = Ui_Chama_Venda()
    ui.setupUi(Chama_Venda)
    Chama_Venda.show()
    sys.exit(app.exec())
