# Form implementation generated from reading ui file 'Form_Edit_Produto.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Edit_Produto(object):
    def setupUi(self, Edit_Produto):
        Edit_Produto.setObjectName("Edit_Produto")
        Edit_Produto.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Edit_Produto.resize(1000, 500)
        Edit_Produto.setMinimumSize(QtCore.QSize(1000, 500))
        Edit_Produto.setMaximumSize(QtCore.QSize(1000, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../img/produtos-.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Edit_Produto.setWindowIcon(icon)
        self.fr_FormProdutos = QtWidgets.QFrame(parent=Edit_Produto)
        self.fr_FormProdutos.setGeometry(QtCore.QRect(0, 0, 1000, 500))
        self.fr_FormProdutos.setStyleSheet("background: #FFF;\n"
"border: none")
        self.fr_FormProdutos.setObjectName("fr_FormProdutos")
        self.lb_FormProdutos = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos.setGeometry(QtCore.QRect(419, 10, 561, 30))
        self.lb_FormProdutos.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"\n"
"border-bottom: 2px solid #A2A2A2\n"
"}")
        self.lb_FormProdutos.setObjectName("lb_FormProdutos")
        self.lb_FotoProduto = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FotoProduto.setGeometry(QtCore.QRect(20, 20, 331, 421))
        self.lb_FotoProduto.setStyleSheet("border: 1px solid #A2A2A2;\n"
"background: url(\'Images/icon/Photo.svg\') center no-repeat \n"
"")
        self.lb_FotoProduto.setText("")
        self.lb_FotoProduto.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_FotoProduto.setObjectName("lb_FotoProduto")
        self.lb_FormProdutos_2 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_2.setGeometry(QtCore.QRect(420, 60, 150, 20))
        self.lb_FormProdutos_2.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_2.setObjectName("lb_FormProdutos_2")
        self.tx_DescricaoProduto = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_DescricaoProduto.setGeometry(QtCore.QRect(420, 85, 450, 25))
        self.tx_DescricaoProduto.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_DescricaoProduto.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_DescricaoProduto.setClearButtonEnabled(True)
        self.tx_DescricaoProduto.setObjectName("tx_DescricaoProduto")
        self.lb_FormProdutos_3 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_3.setGeometry(QtCore.QRect(420, 120, 215, 20))
        self.lb_FormProdutos_3.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_3.setObjectName("lb_FormProdutos_3")
        self.lb_FormProdutos_4 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_4.setGeometry(QtCore.QRect(650, 120, 215, 20))
        self.lb_FormProdutos_4.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_4.setObjectName("lb_FormProdutos_4")
        self.lb_FormProdutos_5 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_5.setGeometry(QtCore.QRect(420, 180, 215, 20))
        self.lb_FormProdutos_5.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_5.setObjectName("lb_FormProdutos_5")
        self.lb_FormProdutos_6 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_6.setGeometry(QtCore.QRect(650, 180, 215, 20))
        self.lb_FormProdutos_6.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_6.setObjectName("lb_FormProdutos_6")
        self.tx_EstoqueMinimoProduto = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_EstoqueMinimoProduto.setGeometry(QtCore.QRect(420, 205, 211, 25))
        self.tx_EstoqueMinimoProduto.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_EstoqueMinimoProduto.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_EstoqueMinimoProduto.setText("")
        self.tx_EstoqueMinimoProduto.setPlaceholderText("")
        self.tx_EstoqueMinimoProduto.setClearButtonEnabled(True)
        self.tx_EstoqueMinimoProduto.setObjectName("tx_EstoqueMinimoProduto")
        self.tx_Codigo = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_Codigo.setGeometry(QtCore.QRect(650, 205, 221, 25))
        self.tx_Codigo.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Codigo.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Codigo.setPlaceholderText("")
        self.tx_Codigo.setClearButtonEnabled(True)
        self.tx_Codigo.setObjectName("tx_Codigo")
        self.lb_FormProdutos_8 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_8.setGeometry(QtCore.QRect(419, 260, 561, 31))
        self.lb_FormProdutos_8.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: normal;\n"
"\n"
"border-bottom: 2px solid #A2A2A2;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_8.setObjectName("lb_FormProdutos_8")
        self.tx_Preco = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_Preco.setGeometry(QtCore.QRect(420, 330, 150, 30))
        self.tx_Preco.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Preco.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 14px \"Arial\" ;\n"
"text-transform: uppercase;\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Preco.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_Preco.setClearButtonEnabled(True)
        self.tx_Preco.setObjectName("tx_Preco")
        self.lb_FormProdutos_10 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_10.setGeometry(QtCore.QRect(420, 310, 50, 20))
        self.lb_FormProdutos_10.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_10.setObjectName("lb_FormProdutos_10")
        self.tx_ValorVarejoProduto = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_ValorVarejoProduto.setGeometry(QtCore.QRect(650, 330, 150, 30))
        self.tx_ValorVarejoProduto.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_ValorVarejoProduto.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 14px \"Arial\" ;\n"
"text-transform: uppercase;\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_ValorVarejoProduto.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_ValorVarejoProduto.setClearButtonEnabled(True)
        self.tx_ValorVarejoProduto.setObjectName("tx_ValorVarejoProduto")
        self.lb_FormProdutos_12 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_12.setGeometry(QtCore.QRect(650, 310, 150, 20))
        self.lb_FormProdutos_12.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_12.setObjectName("lb_FormProdutos_12")
        self.lb_FormProdutos_13 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_13.setGeometry(QtCore.QRect(420, 390, 150, 20))
        self.lb_FormProdutos_13.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_13.setObjectName("lb_FormProdutos_13")
        self.tx_ValorAtacadoProduto = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_ValorAtacadoProduto.setGeometry(QtCore.QRect(420, 410, 150, 30))
        self.tx_ValorAtacadoProduto.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_ValorAtacadoProduto.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 14px \"Arial\" ;\n"
"text-transform: uppercase;\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_ValorAtacadoProduto.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_ValorAtacadoProduto.setClearButtonEnabled(True)
        self.tx_ValorAtacadoProduto.setObjectName("tx_ValorAtacadoProduto")
        self.fr_BotoesFormProdutos = QtWidgets.QFrame(parent=self.fr_FormProdutos)
        self.fr_BotoesFormProdutos.setGeometry(QtCore.QRect(0, 470, 1000, 30))
        self.fr_BotoesFormProdutos.setStyleSheet("background:#E1DFE0;\n"
"border: none;")
        self.fr_BotoesFormProdutos.setObjectName("fr_BotoesFormProdutos")
        self.bt_CancelarProdutos = QtWidgets.QPushButton(parent=self.fr_BotoesFormProdutos)
        self.bt_CancelarProdutos.setGeometry(QtCore.QRect(880, 0, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_CancelarProdutos.setFont(font)
        self.bt_CancelarProdutos.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_CancelarProdutos.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.bt_CancelarProdutos.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.bt_CancelarProdutos.setStyleSheet("QPushButton {\n"
"background-color: #1E87F0;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/sair/delete_delete_exit_1577.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_CancelarProdutos.setIcon(icon1)
        self.bt_CancelarProdutos.setIconSize(QtCore.QSize(75, 25))
        self.bt_CancelarProdutos.setObjectName("bt_CancelarProdutos")
        self.bt_SalvarProdutos = QtWidgets.QPushButton(parent=self.fr_BotoesFormProdutos)
        self.bt_SalvarProdutos.setGeometry(QtCore.QRect(750, 0, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_SalvarProdutos.setFont(font)
        self.bt_SalvarProdutos.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_SalvarProdutos.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.bt_SalvarProdutos.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.bt_SalvarProdutos.setStyleSheet("QPushButton {\n"
"background-color: #7AB32E;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/salvar/salvar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_SalvarProdutos.setIcon(icon2)
        self.bt_SalvarProdutos.setIconSize(QtCore.QSize(50, 25))
        self.bt_SalvarProdutos.setObjectName("bt_SalvarProdutos")
        self.lb_qtdeMin = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_qtdeMin.setGeometry(QtCore.QRect(890, 350, 40, 35))
        self.lb_qtdeMin.setText("")
        self.lb_qtdeMin.setObjectName("lb_qtdeMin")
        self.tx_AddMarca = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_AddMarca.setGeometry(QtCore.QRect(650, 145, 221, 25))
        self.tx_AddMarca.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_AddMarca.setClearButtonEnabled(True)
        self.tx_AddMarca.setObjectName("tx_AddMarca")
        self.tx_AddCategoria = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_AddCategoria.setGeometry(QtCore.QRect(420, 145, 211, 25))
        self.tx_AddCategoria.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_AddCategoria.setInputMask("")
        self.tx_AddCategoria.setObjectName("tx_AddCategoria")
        self.bt_Update_Img = QtWidgets.QPushButton(parent=self.fr_FormProdutos)
        self.bt_Update_Img.setGeometry(QtCore.QRect(20, 410, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bt_Update_Img.setFont(font)
        self.bt_Update_Img.setStyleSheet("QPushButton{\n"
"background: #7AB32E;\n"
"color: #FFF\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_Update_Img.setObjectName("bt_Update_Img")
        self.tx_MinimoAtacado = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_MinimoAtacado.setGeometry(QtCore.QRect(650, 410, 151, 30))
        self.tx_MinimoAtacado.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_MinimoAtacado.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 12px \"Arial\" ;\n"
"text-transform: uppercase\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_MinimoAtacado.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tx_MinimoAtacado.setPlaceholderText("")
        self.tx_MinimoAtacado.setClearButtonEnabled(True)
        self.tx_MinimoAtacado.setObjectName("tx_MinimoAtacado")
        self.lb_FormProdutos_14 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_14.setGeometry(QtCore.QRect(650, 380, 140, 20))
        self.lb_FormProdutos_14.setStyleSheet("QLabel{\n"
"font-size: 10px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: normal;\n"
"color: red\n"
"}")
        self.lb_FormProdutos_14.setObjectName("lb_FormProdutos_14")
        self.tx_AddMarca.raise_()
        self.tx_AddCategoria.raise_()
        self.lb_FormProdutos.raise_()
        self.lb_FotoProduto.raise_()
        self.lb_FormProdutos_2.raise_()
        self.tx_DescricaoProduto.raise_()
        self.lb_FormProdutos_3.raise_()
        self.lb_FormProdutos_4.raise_()
        self.lb_FormProdutos_5.raise_()
        self.lb_FormProdutos_6.raise_()
        self.tx_EstoqueMinimoProduto.raise_()
        self.tx_Codigo.raise_()
        self.lb_FormProdutos_8.raise_()
        self.tx_Preco.raise_()
        self.lb_FormProdutos_10.raise_()
        self.tx_ValorVarejoProduto.raise_()
        self.lb_FormProdutos_12.raise_()
        self.lb_FormProdutos_13.raise_()
        self.tx_ValorAtacadoProduto.raise_()
        self.fr_BotoesFormProdutos.raise_()
        self.lb_qtdeMin.raise_()
        self.bt_Update_Img.raise_()
        self.tx_MinimoAtacado.raise_()
        self.lb_FormProdutos_14.raise_()

        self.retranslateUi(Edit_Produto)
        QtCore.QMetaObject.connectSlotsByName(Edit_Produto)
        Edit_Produto.setTabOrder(self.tx_DescricaoProduto, self.tx_AddCategoria)
        Edit_Produto.setTabOrder(self.tx_AddCategoria, self.tx_AddMarca)
        Edit_Produto.setTabOrder(self.tx_AddMarca, self.tx_EstoqueMinimoProduto)
        Edit_Produto.setTabOrder(self.tx_EstoqueMinimoProduto, self.tx_Codigo)
        Edit_Produto.setTabOrder(self.tx_Codigo, self.tx_Preco)
        Edit_Produto.setTabOrder(self.tx_Preco, self.tx_ValorVarejoProduto)
        Edit_Produto.setTabOrder(self.tx_ValorVarejoProduto, self.tx_ValorAtacadoProduto)
        Edit_Produto.setTabOrder(self.tx_ValorAtacadoProduto, self.tx_MinimoAtacado)
        Edit_Produto.setTabOrder(self.tx_MinimoAtacado, self.bt_Update_Img)

    def retranslateUi(self, Edit_Produto):
        _translate = QtCore.QCoreApplication.translate
        Edit_Produto.setWindowTitle(_translate("Edit_Produto", "EDITAR PRODUTO"))
        self.lb_FormProdutos.setText(_translate("Edit_Produto", "EDITAR PRODUTO"))
        self.lb_FotoProduto.setToolTip(_translate("Edit_Produto", "Insira uma imagem"))
        self.lb_FormProdutos_2.setText(_translate("Edit_Produto", "DESCRIÇÃO"))
        self.tx_DescricaoProduto.setPlaceholderText(_translate("Edit_Produto", "Descrição Produto"))
        self.lb_FormProdutos_3.setText(_translate("Edit_Produto", "CATEGORIA"))
        self.lb_FormProdutos_4.setText(_translate("Edit_Produto", "MARCA"))
        self.lb_FormProdutos_5.setText(_translate("Edit_Produto", "ESTOQUE"))
        self.lb_FormProdutos_6.setText(_translate("Edit_Produto", "CÓDIGO"))
        self.lb_FormProdutos_8.setText(_translate("Edit_Produto", "PREÇOS"))
        self.tx_Preco.setPlaceholderText(_translate("Edit_Produto", "R$ 0.00"))
        self.lb_FormProdutos_10.setText(_translate("Edit_Produto", "PREÇO"))
        self.tx_ValorVarejoProduto.setPlaceholderText(_translate("Edit_Produto", "R$ 0.00"))
        self.lb_FormProdutos_12.setText(_translate("Edit_Produto", "VENDA VAREJO"))
        self.lb_FormProdutos_13.setText(_translate("Edit_Produto", "VENDA ATACADO"))
        self.tx_ValorAtacadoProduto.setPlaceholderText(_translate("Edit_Produto", "R$ 0.00"))
        self.bt_CancelarProdutos.setText(_translate("Edit_Produto", "CANCELAR"))
        self.bt_SalvarProdutos.setText(_translate("Edit_Produto", "SALVAR"))
        self.tx_AddMarca.setPlaceholderText(_translate("Edit_Produto", "NOVA MARCA"))
        self.tx_AddCategoria.setPlaceholderText(_translate("Edit_Produto", "NOVA CATEGORIA"))
        self.bt_Update_Img.setToolTip(_translate("Edit_Produto", "<html><head/><body><p>Deletar Imagem</p></body></html>"))
        self.bt_Update_Img.setText(_translate("Edit_Produto", "Inserir Imagem"))
        self.lb_FormProdutos_14.setText(_translate("Edit_Produto", "QTDE. MÍNIMA P/ ATACADO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Edit_Produto = QtWidgets.QFrame()
    ui = Ui_Edit_Produto()
    ui.setupUi(Edit_Produto)
    Edit_Produto.show()
    sys.exit(app.exec())
