# Form implementation generated from reading ui file 'Form_add_categoria.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_add_categoria(object):
    def setupUi(self, add_categoria):
        add_categoria.setObjectName("add_categoria")
        add_categoria.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        add_categoria.resize(300, 120)
        add_categoria.setMinimumSize(QtCore.QSize(300, 120))
        add_categoria.setMaximumSize(QtCore.QSize(300, 120))
        add_categoria.setStyleSheet("background-color: rgb(0, 85, 127);")
        self.centralwidget = QtWidgets.QWidget(parent=add_categoria)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(300, 120))
        self.frame.setMaximumSize(QtCore.QSize(300, 120))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.Tx_Descricao = QtWidgets.QLineEdit(parent=self.frame)
        self.Tx_Descricao.setGeometry(QtCore.QRect(30, 47, 241, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tx_Descricao.sizePolicy().hasHeightForWidth())
        self.Tx_Descricao.setSizePolicy(sizePolicy)
        self.Tx_Descricao.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Tx_Descricao.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.Tx_Descricao.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.Tx_Descricao.setPlaceholderText("")
        self.Tx_Descricao.setClearButtonEnabled(True)
        self.Tx_Descricao.setObjectName("Tx_Descricao")
        self.Bt_Salvar = QtWidgets.QPushButton(parent=self.frame)
        self.Bt_Salvar.setGeometry(QtCore.QRect(30, 80, 100, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bt_Salvar.sizePolicy().hasHeightForWidth())
        self.Bt_Salvar.setSizePolicy(sizePolicy)
        self.Bt_Salvar.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Bt_Salvar.setFont(font)
        self.Bt_Salvar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Bt_Salvar.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.Bt_Salvar.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.Bt_Salvar.setStyleSheet("QPushButton {\n"
"background-color: #1E87F0;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 152, 222);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/salvar/salvar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_Salvar.setIcon(icon)
        self.Bt_Salvar.setIconSize(QtCore.QSize(50, 25))
        self.Bt_Salvar.setObjectName("Bt_Salvar")
        self.Bt_Cancelar = QtWidgets.QPushButton(parent=self.frame)
        self.Bt_Cancelar.setGeometry(QtCore.QRect(172, 80, 100, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bt_Cancelar.sizePolicy().hasHeightForWidth())
        self.Bt_Cancelar.setSizePolicy(sizePolicy)
        self.Bt_Cancelar.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Bt_Cancelar.setFont(font)
        self.Bt_Cancelar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Bt_Cancelar.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.Bt_Cancelar.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.Bt_Cancelar.setStyleSheet("QPushButton {\n"
"background-color: rgb(208, 0, 0);\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: rgb(218, 0, 0);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/sair/delete_delete_exit_1577.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_Cancelar.setIcon(icon1)
        self.Bt_Cancelar.setIconSize(QtCore.QSize(75, 25))
        self.Bt_Cancelar.setObjectName("Bt_Cancelar")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(30, 10, 241, 20))
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 127);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        add_categoria.setCentralWidget(self.centralwidget)

        self.retranslateUi(add_categoria)
        QtCore.QMetaObject.connectSlotsByName(add_categoria)

    def retranslateUi(self, add_categoria):
        _translate = QtCore.QCoreApplication.translate
        add_categoria.setWindowTitle(_translate("add_categoria", "CADASTRO DE CATEGORIA"))
        self.Bt_Salvar.setText(_translate("add_categoria", "SALVAR"))
        self.Bt_Cancelar.setText(_translate("add_categoria", "CANCELAR"))
        self.label.setText(_translate("add_categoria", "Adicione Uma nova categoria"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_categoria = QtWidgets.QMainWindow()
    ui = Ui_add_categoria()
    ui.setupUi(add_categoria)
    add_categoria.show()
    sys.exit(app.exec())
