# Form implementation generated from reading ui file 'Form_Cad_Produto.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_Cad_Produtos(object):
    def setupUi(self, Form_Cad_Produtos):
        Form_Cad_Produtos.setObjectName("Form_Cad_Produtos")
        Form_Cad_Produtos.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Form_Cad_Produtos.resize(1000, 710)
        Form_Cad_Produtos.setMinimumSize(QtCore.QSize(1000, 710))
        Form_Cad_Produtos.setMaximumSize(QtCore.QSize(1000, 710))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../img/produtos-.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form_Cad_Produtos.setWindowIcon(icon)
        self.fr_FormProdutos = QtWidgets.QFrame(parent=Form_Cad_Produtos)
        self.fr_FormProdutos.setGeometry(QtCore.QRect(0, 0, 1000, 801))
        self.fr_FormProdutos.setStyleSheet("background: #FFF;\n"
"border: none")
        self.fr_FormProdutos.setObjectName("fr_FormProdutos")
        self.lb_FormProdutos = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos.setGeometry(QtCore.QRect(460, 10, 491, 30))
        self.lb_FormProdutos.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"\n"
"border-bottom: 2px solid #A2A2A2\n"
"}")
        self.lb_FormProdutos.setObjectName("lb_FormProdutos")
        self.lb_FotoProduto = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FotoProduto.setGeometry(QtCore.QRect(20, 20, 421, 631))
        self.lb_FotoProduto.setStyleSheet("border: 1px solid #A2A2A2;\n"
"background: center no-repeat;\n"
"")
        self.lb_FotoProduto.setText("")
        self.lb_FotoProduto.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_FotoProduto.setObjectName("lb_FotoProduto")
        self.lb_FormProdutos_2 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_2.setGeometry(QtCore.QRect(460, 60, 150, 20))
        self.lb_FormProdutos_2.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_2.setObjectName("lb_FormProdutos_2")
        self.tx_DescricaoProduto = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_DescricaoProduto.setGeometry(QtCore.QRect(460, 85, 491, 25))
        self.tx_DescricaoProduto.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_DescricaoProduto.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_DescricaoProduto.setClearButtonEnabled(True)
        self.tx_DescricaoProduto.setObjectName("tx_DescricaoProduto")
        self.lb_FormProdutos_3 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_3.setGeometry(QtCore.QRect(460, 140, 215, 20))
        self.lb_FormProdutos_3.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_3.setObjectName("lb_FormProdutos_3")
        self.cb_CategoriaProduto = QtWidgets.QComboBox(parent=self.fr_FormProdutos)
        self.cb_CategoriaProduto.setGeometry(QtCore.QRect(460, 160, 211, 25))
        self.cb_CategoriaProduto.setStyleSheet("QComboBox{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase\n"
"}\n"
"QComboBox:Focus {\n"
"border: 1px solid red;\n"
"}\n"
" QComboBox::drop-down {\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 25px;\n"
"     border-left-width: 1px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"QComboBox::down-arrow {\n"
"     image: url(\"+self.resourcepath(\'Images/down.png\')+\");\n"
" }\n"
"")
        self.cb_CategoriaProduto.setObjectName("cb_CategoriaProduto")
        self.cb_CategoriaProduto.addItem("")
        self.cb_CategoriaProduto.addItem("")
        self.cb_CategoriaProduto.addItem("")
        self.cb_CategoriaProduto.addItem("")
        self.cb_CategoriaProduto.addItem("")
        self.lb_FormProdutos_4 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_4.setGeometry(QtCore.QRect(760, 140, 191, 20))
        self.lb_FormProdutos_4.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_4.setObjectName("lb_FormProdutos_4")
        self.lb_FormProdutos_5 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_5.setGeometry(QtCore.QRect(460, 240, 215, 20))
        self.lb_FormProdutos_5.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_5.setObjectName("lb_FormProdutos_5")
        self.lb_FormProdutos_6 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_6.setGeometry(QtCore.QRect(760, 240, 181, 20))
        self.lb_FormProdutos_6.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_6.setObjectName("lb_FormProdutos_6")
        self.tx_Estoque = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_Estoque.setGeometry(QtCore.QRect(460, 260, 211, 25))
        self.tx_Estoque.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Estoque.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Estoque.setText("")
        self.tx_Estoque.setPlaceholderText("")
        self.tx_Estoque.setClearButtonEnabled(True)
        self.tx_Estoque.setObjectName("tx_Estoque")
        self.tx_Codigo = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_Codigo.setGeometry(QtCore.QRect(760, 260, 191, 25))
        self.tx_Codigo.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Codigo.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Codigo.setPlaceholderText("")
        self.tx_Codigo.setClearButtonEnabled(True)
        self.tx_Codigo.setObjectName("tx_Codigo")
        self.lb_FormProdutos_8 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_8.setGeometry(QtCore.QRect(460, 330, 491, 21))
        self.lb_FormProdutos_8.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: normal;\n"
"\n"
"border-bottom: 2px solid #A2A2A2;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_8.setObjectName("lb_FormProdutos_8")
        self.tx_Preco_Produto = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_Preco_Produto.setGeometry(QtCore.QRect(460, 420, 211, 30))
        self.tx_Preco_Produto.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Preco_Produto.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 14px \"Arial\" ;\n"
"text-transform: uppercase;\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Preco_Produto.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_Preco_Produto.setClearButtonEnabled(True)
        self.tx_Preco_Produto.setObjectName("tx_Preco_Produto")
        self.lb_FormProdutos_10 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_10.setGeometry(QtCore.QRect(460, 390, 50, 20))
        self.lb_FormProdutos_10.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_10.setObjectName("lb_FormProdutos_10")
        self.tx_Venda_Varejo = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_Venda_Varejo.setGeometry(QtCore.QRect(760, 420, 191, 30))
        self.tx_Venda_Varejo.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Venda_Varejo.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 14px \"Arial\" ;\n"
"text-transform: uppercase;\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Venda_Varejo.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_Venda_Varejo.setClearButtonEnabled(True)
        self.tx_Venda_Varejo.setObjectName("tx_Venda_Varejo")
        self.lb_FormProdutos_12 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_12.setGeometry(QtCore.QRect(760, 390, 150, 20))
        self.lb_FormProdutos_12.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_12.setObjectName("lb_FormProdutos_12")
        self.lb_FormProdutos_13 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_13.setGeometry(QtCore.QRect(460, 520, 150, 20))
        self.lb_FormProdutos_13.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_13.setObjectName("lb_FormProdutos_13")
        self.tx_Venda_Atacado = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_Venda_Atacado.setGeometry(QtCore.QRect(460, 550, 211, 30))
        self.tx_Venda_Atacado.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Venda_Atacado.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 14px \"Arial\" ;\n"
"text-transform: uppercase;\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Venda_Atacado.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_Venda_Atacado.setClearButtonEnabled(True)
        self.tx_Venda_Atacado.setObjectName("tx_Venda_Atacado")
        self.tx_MinimoAtacado = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_MinimoAtacado.setGeometry(QtCore.QRect(760, 550, 191, 30))
        self.tx_MinimoAtacado.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_MinimoAtacado.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 12px \"Arial\" ;\n"
"text-transform: uppercase\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_MinimoAtacado.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tx_MinimoAtacado.setPlaceholderText("")
        self.tx_MinimoAtacado.setClearButtonEnabled(True)
        self.tx_MinimoAtacado.setObjectName("tx_MinimoAtacado")
        self.lb_FormProdutos_14 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos_14.setGeometry(QtCore.QRect(760, 520, 140, 20))
        self.lb_FormProdutos_14.setStyleSheet("QLabel{\n"
"font-size: 10px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: normal;\n"
"color: red\n"
"}")
        self.lb_FormProdutos_14.setObjectName("lb_FormProdutos_14")
        self.tx_Marca = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_Marca.setGeometry(QtCore.QRect(760, 160, 190, 25))
        self.tx_Marca.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Marca.setClearButtonEnabled(True)
        self.tx_Marca.setObjectName("tx_Marca")
        self.bt_AddImagem = QtWidgets.QPushButton(parent=self.fr_FormProdutos)
        self.bt_AddImagem.setGeometry(QtCore.QRect(20, 650, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_AddImagem.setFont(font)
        self.bt_AddImagem.setStyleSheet("QPushButton{\n"
"font: 14pt \"Roboto\";\n"
"background: #7AB32E;\n"
"color: #FFF\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}\n"
"font: 12pt \"Roboto\";")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/sair/delete_delete_exit_1577.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_AddImagem.setIcon(icon1)
        self.bt_AddImagem.setObjectName("bt_AddImagem")
        self.fr_BotoesFormProdutos = QtWidgets.QFrame(parent=self.fr_FormProdutos)
        self.fr_BotoesFormProdutos.setGeometry(QtCore.QRect(0, 680, 1001, 31))
        self.fr_BotoesFormProdutos.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"border: none;")
        self.fr_BotoesFormProdutos.setObjectName("fr_BotoesFormProdutos")
        self.Bt_SalvarProdutos = QtWidgets.QPushButton(parent=self.fr_BotoesFormProdutos)
        self.Bt_SalvarProdutos.setGeometry(QtCore.QRect(690, 0, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Bt_SalvarProdutos.setFont(font)
        self.Bt_SalvarProdutos.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Bt_SalvarProdutos.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.Bt_SalvarProdutos.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.Bt_SalvarProdutos.setStyleSheet("QPushButton {\n"
"background-color: #7AB32E;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/salvar/salvar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_SalvarProdutos.setIcon(icon2)
        self.Bt_SalvarProdutos.setIconSize(QtCore.QSize(50, 25))
        self.Bt_SalvarProdutos.setObjectName("Bt_SalvarProdutos")
        self.Bt_CancelarProdutos = QtWidgets.QPushButton(parent=self.fr_BotoesFormProdutos)
        self.Bt_CancelarProdutos.setGeometry(QtCore.QRect(820, 0, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Bt_CancelarProdutos.setFont(font)
        self.Bt_CancelarProdutos.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Bt_CancelarProdutos.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.Bt_CancelarProdutos.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.Bt_CancelarProdutos.setStyleSheet("QPushButton {\n"
"background-color: #1E87F0;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.Bt_CancelarProdutos.setIcon(icon1)
        self.Bt_CancelarProdutos.setIconSize(QtCore.QSize(75, 25))
        self.Bt_CancelarProdutos.setObjectName("Bt_CancelarProdutos")
        self.tx_Marca.raise_()
        self.lb_FormProdutos.raise_()
        self.lb_FotoProduto.raise_()
        self.lb_FormProdutos_2.raise_()
        self.tx_DescricaoProduto.raise_()
        self.lb_FormProdutos_3.raise_()
        self.cb_CategoriaProduto.raise_()
        self.lb_FormProdutos_4.raise_()
        self.lb_FormProdutos_5.raise_()
        self.lb_FormProdutos_6.raise_()
        self.tx_Estoque.raise_()
        self.tx_Codigo.raise_()
        self.lb_FormProdutos_8.raise_()
        self.tx_Preco_Produto.raise_()
        self.lb_FormProdutos_10.raise_()
        self.tx_Venda_Varejo.raise_()
        self.lb_FormProdutos_12.raise_()
        self.lb_FormProdutos_13.raise_()
        self.tx_Venda_Atacado.raise_()
        self.tx_MinimoAtacado.raise_()
        self.lb_FormProdutos_14.raise_()
        self.bt_AddImagem.raise_()
        self.fr_BotoesFormProdutos.raise_()

        self.retranslateUi(Form_Cad_Produtos)
        QtCore.QMetaObject.connectSlotsByName(Form_Cad_Produtos)
        Form_Cad_Produtos.setTabOrder(self.tx_DescricaoProduto, self.cb_CategoriaProduto)
        Form_Cad_Produtos.setTabOrder(self.cb_CategoriaProduto, self.tx_Marca)
        Form_Cad_Produtos.setTabOrder(self.tx_Marca, self.tx_Estoque)
        Form_Cad_Produtos.setTabOrder(self.tx_Estoque, self.tx_Codigo)
        Form_Cad_Produtos.setTabOrder(self.tx_Codigo, self.tx_Preco_Produto)
        Form_Cad_Produtos.setTabOrder(self.tx_Preco_Produto, self.tx_Venda_Varejo)
        Form_Cad_Produtos.setTabOrder(self.tx_Venda_Varejo, self.tx_Venda_Atacado)
        Form_Cad_Produtos.setTabOrder(self.tx_Venda_Atacado, self.tx_MinimoAtacado)
        Form_Cad_Produtos.setTabOrder(self.tx_MinimoAtacado, self.bt_AddImagem)

    def retranslateUi(self, Form_Cad_Produtos):
        _translate = QtCore.QCoreApplication.translate
        Form_Cad_Produtos.setWindowTitle(_translate("Form_Cad_Produtos", "CADASTRO PRODUTOS"))
        self.lb_FormProdutos.setText(_translate("Form_Cad_Produtos", "CADASTRAR PRODUTO"))
        self.lb_FotoProduto.setToolTip(_translate("Form_Cad_Produtos", "Insira uma imagem"))
        self.lb_FormProdutos_2.setText(_translate("Form_Cad_Produtos", "DESCRIÇÃO"))
        self.tx_DescricaoProduto.setPlaceholderText(_translate("Form_Cad_Produtos", "DESCRIÇÃO DO PRODUTO"))
        self.lb_FormProdutos_3.setText(_translate("Form_Cad_Produtos", "CATEGORIA"))
        self.cb_CategoriaProduto.setItemText(0, _translate("Form_Cad_Produtos", "SELECIONE"))
        self.cb_CategoriaProduto.setItemText(1, _translate("Form_Cad_Produtos", "ALIMENTOS "))
        self.cb_CategoriaProduto.setItemText(2, _translate("Form_Cad_Produtos", "BEBIDAS"))
        self.cb_CategoriaProduto.setItemText(3, _translate("Form_Cad_Produtos", "INFORMÁTICA"))
        self.cb_CategoriaProduto.setItemText(4, _translate("Form_Cad_Produtos", "ELETRÔNICOS"))
        self.lb_FormProdutos_4.setText(_translate("Form_Cad_Produtos", "MARCA"))
        self.lb_FormProdutos_5.setText(_translate("Form_Cad_Produtos", "ESTOQUE"))
        self.lb_FormProdutos_6.setText(_translate("Form_Cad_Produtos", "CÓDIGO"))
        self.lb_FormProdutos_8.setText(_translate("Form_Cad_Produtos", "PREÇOS"))
        self.tx_Preco_Produto.setPlaceholderText(_translate("Form_Cad_Produtos", "R$ 0.00"))
        self.lb_FormProdutos_10.setText(_translate("Form_Cad_Produtos", "PREÇO"))
        self.tx_Venda_Varejo.setPlaceholderText(_translate("Form_Cad_Produtos", "R$ 0.00"))
        self.lb_FormProdutos_12.setText(_translate("Form_Cad_Produtos", "VENDA VAREJO"))
        self.lb_FormProdutos_13.setText(_translate("Form_Cad_Produtos", "VENDA ATACADO"))
        self.tx_Venda_Atacado.setPlaceholderText(_translate("Form_Cad_Produtos", "R$ 0.00"))
        self.lb_FormProdutos_14.setText(_translate("Form_Cad_Produtos", "QTDE. MÍNIMA P/ ATACADO"))
        self.tx_Marca.setPlaceholderText(_translate("Form_Cad_Produtos", "NOVA MARCA"))
        self.bt_AddImagem.setToolTip(_translate("Form_Cad_Produtos", "<html><head/><body><p>CADASTRAR IMGEM</p></body></html>"))
        self.bt_AddImagem.setText(_translate("Form_Cad_Produtos", "Inserir Imagem"))
        self.Bt_SalvarProdutos.setText(_translate("Form_Cad_Produtos", "SALVAR"))
        self.Bt_CancelarProdutos.setText(_translate("Form_Cad_Produtos", "CANCELAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_Cad_Produtos = QtWidgets.QFrame()
    ui = Ui_Form_Cad_Produtos()
    ui.setupUi(Form_Cad_Produtos)
    Form_Cad_Produtos.show()
    sys.exit(app.exec())
