# Form implementation generated from reading ui file 'Form_Consulta_cnpj.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_Consulta_Cnpj(object):
    def setupUi(self, Form_Consulta_Cnpj):
        Form_Consulta_Cnpj.setObjectName("Form_Consulta_Cnpj")
        Form_Consulta_Cnpj.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Form_Consulta_Cnpj.resize(720, 470)
        Form_Consulta_Cnpj.setMinimumSize(QtCore.QSize(720, 470))
        Form_Consulta_Cnpj.setMaximumSize(QtCore.QSize(1000, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../img/clientes.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form_Consulta_Cnpj.setWindowIcon(icon)
        self.fr_FormClientes = QtWidgets.QFrame(parent=Form_Consulta_Cnpj)
        self.fr_FormClientes.setGeometry(QtCore.QRect(0, 0, 1000, 500))
        self.fr_FormClientes.setStyleSheet("background: #FFF;\n"
"border: none")
        self.fr_FormClientes.setObjectName("fr_FormClientes")
        self.lb_FormProdutos = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos.setGeometry(QtCore.QRect(100, 10, 880, 30))
        self.lb_FormProdutos.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"\n"
"border-bottom: 2px solid #A2A2A2\n"
"}")
        self.lb_FormProdutos.setObjectName("lb_FormProdutos")
        self.tx_Id = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Id.setEnabled(False)
        self.tx_Id.setGeometry(QtCore.QRect(30, 10, 50, 30))
        self.tx_Id.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border: 1px solid #A2A2A2;\n"
"color: #000;\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"\n"
"}")
        self.tx_Id.setText("")
        self.tx_Id.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tx_Id.setObjectName("tx_Id")
        self.Lb_Razao_Social = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.Lb_Razao_Social.setGeometry(QtCore.QRect(360, 60, 150, 20))
        self.Lb_Razao_Social.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.Lb_Razao_Social.setObjectName("Lb_Razao_Social")
        self.tx_Nome = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Nome.setGeometry(QtCore.QRect(360, 90, 321, 25))
        self.tx_Nome.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Nome.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Nome.setObjectName("tx_Nome")
        self.Lb_Cnpj = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.Lb_Cnpj.setGeometry(QtCore.QRect(30, 60, 190, 20))
        self.Lb_Cnpj.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.Lb_Cnpj.setObjectName("Lb_Cnpj")
        self.Lb_Edereco = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.Lb_Edereco.setGeometry(QtCore.QRect(30, 220, 630, 30))
        self.Lb_Edereco.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: normal;\n"
"\n"
"border-bottom: 2px solid #A2A2A2;\n"
"color: #797979\n"
"}")
        self.Lb_Edereco.setObjectName("Lb_Edereco")
        self.tx_Cep = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Cep.setGeometry(QtCore.QRect(30, 300, 100, 25))
        self.tx_Cep.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Cep.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Cep.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tx_Cep.setObjectName("tx_Cep")
        self.Lb_Cep = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.Lb_Cep.setGeometry(QtCore.QRect(30, 270, 50, 20))
        self.Lb_Cep.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.Lb_Cep.setObjectName("Lb_Cep")
        self.fr_BotoesFormProdutos = QtWidgets.QFrame(parent=self.fr_FormClientes)
        self.fr_BotoesFormProdutos.setGeometry(QtCore.QRect(0, 470, 1000, 30))
        self.fr_BotoesFormProdutos.setStyleSheet("background:#E1DFE0;\n"
"border: none;")
        self.fr_BotoesFormProdutos.setObjectName("fr_BotoesFormProdutos")
        self.Tx_Cnpj = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.Tx_Cnpj.setGeometry(QtCore.QRect(30, 90, 271, 25))
        self.Tx_Cnpj.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.Tx_Cnpj.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.Tx_Cnpj.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Tx_Cnpj.setPlaceholderText("")
        self.Tx_Cnpj.setObjectName("Tx_Cnpj")
        self.Lb_Email = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.Lb_Email.setGeometry(QtCore.QRect(30, 140, 190, 20))
        self.Lb_Email.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.Lb_Email.setObjectName("Lb_Email")
        self.Lb_Telefone = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.Lb_Telefone.setGeometry(QtCore.QRect(360, 140, 190, 20))
        self.Lb_Telefone.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.Lb_Telefone.setObjectName("Lb_Telefone")
        self.tx_Email = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Email.setGeometry(QtCore.QRect(30, 170, 301, 25))
        self.tx_Email.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Email.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Email.setPlaceholderText("")
        self.tx_Email.setObjectName("tx_Email")
        self.tx_Telefone = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Telefone.setGeometry(QtCore.QRect(360, 170, 196, 25))
        self.tx_Telefone.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Telefone.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Telefone.setMaxLength(15)
        self.tx_Telefone.setCursorPosition(15)
        self.tx_Telefone.setPlaceholderText("")
        self.tx_Telefone.setObjectName("tx_Telefone")
        self.LB_Logradouro = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.LB_Logradouro.setGeometry(QtCore.QRect(180, 270, 250, 20))
        self.LB_Logradouro.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.LB_Logradouro.setObjectName("LB_Logradouro")
        self.txLogradouro = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.txLogradouro.setGeometry(QtCore.QRect(180, 300, 400, 25))
        self.txLogradouro.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.txLogradouro.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.txLogradouro.setInputMask("")
        self.txLogradouro.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.txLogradouro.setPlaceholderText("")
        self.txLogradouro.setObjectName("txLogradouro")
        self.Lb_Numero = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.Lb_Numero.setGeometry(QtCore.QRect(620, 270, 50, 20))
        self.Lb_Numero.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.Lb_Numero.setObjectName("Lb_Numero")
        self.tx_Numero = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Numero.setGeometry(QtCore.QRect(610, 300, 70, 25))
        self.tx_Numero.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Numero.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Numero.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.tx_Numero.setInputMask("")
        self.tx_Numero.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_Numero.setPlaceholderText("")
        self.tx_Numero.setObjectName("tx_Numero")
        self.tx_Bairro = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Bairro.setGeometry(QtCore.QRect(30, 370, 260, 25))
        self.tx_Bairro.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Bairro.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Bairro.setInputMask("")
        self.tx_Bairro.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_Bairro.setPlaceholderText("")
        self.tx_Bairro.setObjectName("tx_Bairro")
        self.Lb_Bairro = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.Lb_Bairro.setGeometry(QtCore.QRect(30, 350, 120, 20))
        self.Lb_Bairro.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.Lb_Bairro.setObjectName("Lb_Bairro")
        self.tx_municipio = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_municipio.setGeometry(QtCore.QRect(320, 370, 260, 25))
        self.tx_municipio.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_municipio.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_municipio.setInputMask("")
        self.tx_municipio.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_municipio.setPlaceholderText("")
        self.tx_municipio.setObjectName("tx_municipio")
        self.Lb_Municipio = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.Lb_Municipio.setGeometry(QtCore.QRect(320, 350, 120, 20))
        self.Lb_Municipio.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.Lb_Municipio.setObjectName("Lb_Municipio")
        self.Lb_Uf = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.Lb_Uf.setGeometry(QtCore.QRect(610, 350, 70, 20))
        self.Lb_Uf.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.Lb_Uf.setObjectName("Lb_Uf")
        self.tx_Uf = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Uf.setGeometry(QtCore.QRect(610, 370, 70, 25))
        self.tx_Uf.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Uf.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Uf.setInputMask("")
        self.tx_Uf.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_Uf.setPlaceholderText("")
        self.tx_Uf.setObjectName("tx_Uf")
        self.bt_BuscaCep_2 = QtWidgets.QPushButton(parent=self.fr_FormClientes)
        self.bt_BuscaCep_2.setGeometry(QtCore.QRect(130, 300, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bt_BuscaCep_2.setFont(font)
        self.bt_BuscaCep_2.setStyleSheet("QPushButton{\n"
"background: #7AB32E;\n"
"color: #FFF\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_BuscaCep_2.setText("")
        self.bt_BuscaCep_2.setObjectName("bt_BuscaCep_2")
        self.Bt_Salvar = QtWidgets.QPushButton(parent=self.fr_FormClientes)
        self.Bt_Salvar.setGeometry(QtCore.QRect(420, 430, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Bt_Salvar.setFont(font)
        self.Bt_Salvar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Bt_Salvar.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.Bt_Salvar.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.Bt_Salvar.setStyleSheet("QPushButton {\n"
"background-color: #7AB32E;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/salvar/salvar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_Salvar.setIcon(icon1)
        self.Bt_Salvar.setIconSize(QtCore.QSize(50, 25))
        self.Bt_Salvar.setObjectName("Bt_Salvar")
        self.Bt_Voltar = QtWidgets.QPushButton(parent=self.fr_FormClientes)
        self.Bt_Voltar.setGeometry(QtCore.QRect(560, 430, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Bt_Voltar.setFont(font)
        self.Bt_Voltar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Bt_Voltar.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.Bt_Voltar.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.Bt_Voltar.setStyleSheet("QPushButton {\n"
"background-color: #1E87F0;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/sair/delete_delete_exit_1577.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_Voltar.setIcon(icon2)
        self.Bt_Voltar.setIconSize(QtCore.QSize(75, 25))
        self.Bt_Voltar.setObjectName("Bt_Voltar")
        self.Bt_Consultar_Cnpj = QtWidgets.QPushButton(parent=self.fr_FormClientes)
        self.Bt_Consultar_Cnpj.setGeometry(QtCore.QRect(310, 88, 31, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bt_Consultar_Cnpj.sizePolicy().hasHeightForWidth())
        self.Bt_Consultar_Cnpj.setSizePolicy(sizePolicy)
        self.Bt_Consultar_Cnpj.setMinimumSize(QtCore.QSize(0, 25))
        self.Bt_Consultar_Cnpj.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Bt_Consultar_Cnpj.setStyleSheet("QPushButton {\n"
"border:none;\n"
" }\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.Bt_Consultar_Cnpj.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/pesquisar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_Consultar_Cnpj.setIcon(icon3)
        self.Bt_Consultar_Cnpj.setIconSize(QtCore.QSize(21, 25))
        self.Bt_Consultar_Cnpj.setObjectName("Bt_Consultar_Cnpj")

        self.retranslateUi(Form_Consulta_Cnpj)
        QtCore.QMetaObject.connectSlotsByName(Form_Consulta_Cnpj)
        Form_Consulta_Cnpj.setTabOrder(self.tx_Id, self.Tx_Cnpj)
        Form_Consulta_Cnpj.setTabOrder(self.Tx_Cnpj, self.tx_Nome)
        Form_Consulta_Cnpj.setTabOrder(self.tx_Nome, self.tx_Email)
        Form_Consulta_Cnpj.setTabOrder(self.tx_Email, self.tx_Telefone)
        Form_Consulta_Cnpj.setTabOrder(self.tx_Telefone, self.tx_Cep)
        Form_Consulta_Cnpj.setTabOrder(self.tx_Cep, self.txLogradouro)
        Form_Consulta_Cnpj.setTabOrder(self.txLogradouro, self.tx_Numero)
        Form_Consulta_Cnpj.setTabOrder(self.tx_Numero, self.tx_Bairro)
        Form_Consulta_Cnpj.setTabOrder(self.tx_Bairro, self.tx_municipio)
        Form_Consulta_Cnpj.setTabOrder(self.tx_municipio, self.tx_Uf)
        Form_Consulta_Cnpj.setTabOrder(self.tx_Uf, self.bt_BuscaCep_2)

    def retranslateUi(self, Form_Consulta_Cnpj):
        _translate = QtCore.QCoreApplication.translate
        Form_Consulta_Cnpj.setWindowTitle(_translate("Form_Consulta_Cnpj", "LC INFORMÁTICA| CADASTRO CLIENTE"))
        self.lb_FormProdutos.setText(_translate("Form_Consulta_Cnpj", "CONSULTAR CNPJ"))
        self.Lb_Razao_Social.setText(_translate("Form_Consulta_Cnpj", "RAZÃO SOCIAL"))
        self.tx_Nome.setPlaceholderText(_translate("Form_Consulta_Cnpj", "NOME COMPLETO"))
        self.Lb_Cnpj.setText(_translate("Form_Consulta_Cnpj", "CNPJ"))
        self.Lb_Edereco.setText(_translate("Form_Consulta_Cnpj", "ENDEREÇO"))
        self.tx_Cep.setInputMask(_translate("Form_Consulta_Cnpj", "99999-999"))
        self.tx_Cep.setPlaceholderText(_translate("Form_Consulta_Cnpj", "123456789"))
        self.Lb_Cep.setText(_translate("Form_Consulta_Cnpj", "CEP"))
        self.Tx_Cnpj.setInputMask(_translate("Form_Consulta_Cnpj", "00.000.000/0000-00"))
        self.Tx_Cnpj.setText(_translate("Form_Consulta_Cnpj", "../-"))
        self.Lb_Email.setText(_translate("Form_Consulta_Cnpj", "Email"))
        self.Lb_Telefone.setText(_translate("Form_Consulta_Cnpj", "TELEFONE"))
        self.tx_Telefone.setInputMask(_translate("Form_Consulta_Cnpj", "(00) 0000-00000"))
        self.tx_Telefone.setText(_translate("Form_Consulta_Cnpj", "() -"))
        self.LB_Logradouro.setText(_translate("Form_Consulta_Cnpj", "LOGRADOURO"))
        self.Lb_Numero.setText(_translate("Form_Consulta_Cnpj", "Nº"))
        self.Lb_Bairro.setText(_translate("Form_Consulta_Cnpj", "BAIRRO"))
        self.Lb_Municipio.setText(_translate("Form_Consulta_Cnpj", "MUNICIPIO"))
        self.Lb_Uf.setText(_translate("Form_Consulta_Cnpj", "UF"))
        self.Bt_Salvar.setText(_translate("Form_Consulta_Cnpj", "SALVAR"))
        self.Bt_Voltar.setText(_translate("Form_Consulta_Cnpj", "SAIR"))
        self.Bt_Consultar_Cnpj.setToolTip(_translate("Form_Consulta_Cnpj", "Pesquisar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_Consulta_Cnpj = QtWidgets.QFrame()
    ui = Ui_Form_Consulta_Cnpj()
    ui.setupUi(Form_Consulta_Cnpj)
    Form_Consulta_Cnpj.show()
    sys.exit(app.exec())
