# Form implementation generated from reading ui file 'Form_Cad_Clientes.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_Cad_Clientes(object):
    def setupUi(self, Form_Cad_Clientes):
        Form_Cad_Clientes.setObjectName("Form_Cad_Clientes")
        Form_Cad_Clientes.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Form_Cad_Clientes.resize(675, 500)
        Form_Cad_Clientes.setMinimumSize(QtCore.QSize(675, 500))
        Form_Cad_Clientes.setMaximumSize(QtCore.QSize(675, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../img/clientes.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form_Cad_Clientes.setWindowIcon(icon)
        self.fr_FormClientes = QtWidgets.QFrame(parent=Form_Cad_Clientes)
        self.fr_FormClientes.setGeometry(QtCore.QRect(0, 0, 1000, 500))
        self.fr_FormClientes.setStyleSheet("background: #FFF;\n"
"border: none")
        self.fr_FormClientes.setObjectName("fr_FormClientes")
        self.lb_FormProdutos = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos.setGeometry(QtCore.QRect(80, 10, 561, 30))
        self.lb_FormProdutos.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"\n"
"border-bottom: 2px solid #A2A2A2\n"
"}")
        self.lb_FormProdutos.setObjectName("lb_FormProdutos")
        self.tx_Id = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Id.setEnabled(False)
        self.tx_Id.setGeometry(QtCore.QRect(20, 10, 50, 30))
        self.tx_Id.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border: 1px solid #A2A2A2;\n"
"color: #000;\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"\n"
"}")
        self.tx_Id.setText("")
        self.tx_Id.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tx_Id.setObjectName("tx_Id")
        self.lb_FormProdutos_2 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_2.setGeometry(QtCore.QRect(20, 60, 150, 20))
        self.lb_FormProdutos_2.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_2.setObjectName("lb_FormProdutos_2")
        self.tx_Nome = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Nome.setGeometry(QtCore.QRect(20, 85, 631, 25))
        self.tx_Nome.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Nome.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Nome.setObjectName("tx_Nome")
        self.lb_FormProdutos_3 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_3.setGeometry(QtCore.QRect(20, 120, 190, 20))
        self.lb_FormProdutos_3.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_3.setObjectName("lb_FormProdutos_3")
        self.lb_FormProdutos_4 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_4.setGeometry(QtCore.QRect(236, 120, 190, 20))
        self.lb_FormProdutos_4.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_4.setObjectName("lb_FormProdutos_4")
        self.tx_rg = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_rg.setGeometry(QtCore.QRect(230, 150, 196, 25))
        self.tx_rg.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_rg.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_rg.setPlaceholderText("")
        self.tx_rg.setObjectName("tx_rg")
        self.lb_FormProdutos_8 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_8.setGeometry(QtCore.QRect(20, 270, 630, 30))
        self.lb_FormProdutos_8.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: normal;\n"
"\n"
"border-bottom: 2px solid #A2A2A2;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_8.setObjectName("lb_FormProdutos_8")
        self.tx_Cep = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Cep.setGeometry(QtCore.QRect(20, 360, 100, 25))
        self.tx_Cep.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Cep.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Cep.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tx_Cep.setObjectName("tx_Cep")
        self.lb_FormProdutos_10 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_10.setGeometry(QtCore.QRect(20, 335, 50, 20))
        self.lb_FormProdutos_10.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_10.setObjectName("lb_FormProdutos_10")
        self.fr_BotoesFormProdutos = QtWidgets.QFrame(parent=self.fr_FormClientes)
        self.fr_BotoesFormProdutos.setGeometry(QtCore.QRect(0, 470, 1000, 30))
        self.fr_BotoesFormProdutos.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"border: none;")
        self.fr_BotoesFormProdutos.setObjectName("fr_BotoesFormProdutos")
        self.Bt_Voltar = QtWidgets.QPushButton(parent=self.fr_BotoesFormProdutos)
        self.Bt_Voltar.setGeometry(QtCore.QRect(550, 0, 101, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Bt_Voltar.setFont(font)
        self.Bt_Voltar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Bt_Voltar.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.Bt_Voltar.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.Bt_Voltar.setStyleSheet("QPushButton {\n"
"background-color: rgb(193, 0, 0);\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 85, 0);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/sair/delete_delete_exit_1577.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_Voltar.setIcon(icon1)
        self.Bt_Voltar.setIconSize(QtCore.QSize(75, 25))
        self.Bt_Voltar.setObjectName("Bt_Voltar")
        self.Bt_Salvar = QtWidgets.QPushButton(parent=self.fr_BotoesFormProdutos)
        self.Bt_Salvar.setGeometry(QtCore.QRect(430, 0, 101, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Bt_Salvar.setFont(font)
        self.Bt_Salvar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Bt_Salvar.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.Bt_Salvar.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.Bt_Salvar.setStyleSheet("QPushButton {\n"
"background-color: #40a286;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #7AB32E;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/salvar/salvar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_Salvar.setIcon(icon2)
        self.Bt_Salvar.setIconSize(QtCore.QSize(50, 25))
        self.Bt_Salvar.setObjectName("Bt_Salvar")
        self.tx_cpf = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_cpf.setGeometry(QtCore.QRect(20, 150, 196, 25))
        self.tx_cpf.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_cpf.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_cpf.setPlaceholderText("")
        self.tx_cpf.setObjectName("tx_cpf")
        self.lb_FormProdutos_23 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_23.setGeometry(QtCore.QRect(350, 200, 191, 20))
        self.lb_FormProdutos_23.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_23.setObjectName("lb_FormProdutos_23")
        self.lb_FormProdutos_24 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_24.setGeometry(QtCore.QRect(20, 200, 190, 20))
        self.lb_FormProdutos_24.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_24.setObjectName("lb_FormProdutos_24")
        self.tx_Email = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Email.setGeometry(QtCore.QRect(345, 220, 301, 25))
        self.tx_Email.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Email.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Email.setPlaceholderText("")
        self.tx_Email.setObjectName("tx_Email")
        self.tx_Telefone = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Telefone.setGeometry(QtCore.QRect(20, 220, 301, 25))
        self.tx_Telefone.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Telefone.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Telefone.setMaxLength(15)
        self.tx_Telefone.setCursorPosition(15)
        self.tx_Telefone.setPlaceholderText("")
        self.tx_Telefone.setObjectName("tx_Telefone")
        self.lb_FormProdutos_11 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_11.setGeometry(QtCore.QRect(160, 335, 250, 20))
        self.lb_FormProdutos_11.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_11.setObjectName("lb_FormProdutos_11")
        self.tx_Endereco = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Endereco.setGeometry(QtCore.QRect(160, 360, 400, 25))
        self.tx_Endereco.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Endereco.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Endereco.setInputMask("")
        self.tx_Endereco.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_Endereco.setPlaceholderText("")
        self.tx_Endereco.setObjectName("tx_Endereco")
        self.lb_FormProdutos_12 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_12.setGeometry(QtCore.QRect(580, 335, 50, 20))
        self.lb_FormProdutos_12.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_12.setObjectName("lb_FormProdutos_12")
        self.tx_Numero = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Numero.setGeometry(QtCore.QRect(580, 360, 70, 25))
        self.tx_Numero.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Numero.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Numero.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.tx_Numero.setInputMask("")
        self.tx_Numero.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_Numero.setPlaceholderText("")
        self.tx_Numero.setObjectName("tx_Numero")
        self.tx_Bairro = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Bairro.setGeometry(QtCore.QRect(20, 415, 260, 25))
        self.tx_Bairro.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Bairro.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Bairro.setInputMask("")
        self.tx_Bairro.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_Bairro.setPlaceholderText("")
        self.tx_Bairro.setObjectName("tx_Bairro")
        self.lb_FormProdutos_13 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_13.setGeometry(QtCore.QRect(20, 390, 120, 20))
        self.lb_FormProdutos_13.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_13.setObjectName("lb_FormProdutos_13")
        self.tx_Cidade = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Cidade.setGeometry(QtCore.QRect(300, 415, 260, 25))
        self.tx_Cidade.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Cidade.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Cidade.setInputMask("")
        self.tx_Cidade.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_Cidade.setPlaceholderText("")
        self.tx_Cidade.setObjectName("tx_Cidade")
        self.lb_FormProdutos_14 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_14.setGeometry(QtCore.QRect(300, 390, 120, 20))
        self.lb_FormProdutos_14.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_14.setObjectName("lb_FormProdutos_14")
        self.lb_FormProdutos_15 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_15.setGeometry(QtCore.QRect(580, 390, 70, 20))
        self.lb_FormProdutos_15.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_15.setObjectName("lb_FormProdutos_15")
        self.tx_Estado = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Estado.setGeometry(QtCore.QRect(580, 415, 70, 25))
        self.tx_Estado.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Estado.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Estado.setInputMask("")
        self.tx_Estado.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_Estado.setPlaceholderText("")
        self.tx_Estado.setObjectName("tx_Estado")
        self.bt_BuscaCep = QtWidgets.QPushButton(parent=self.fr_FormClientes)
        self.bt_BuscaCep.setGeometry(QtCore.QRect(120, 360, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bt_BuscaCep.setFont(font)
        self.bt_BuscaCep.setStyleSheet("QPushButton{\n"
"background: #CFCFCF;\n"
"color: #FFF\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(145, 145, 145);\n"
"}\n"
"image: url(:/pesquisar/fsdfs.png);")
        self.bt_BuscaCep.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pesquisar/fsdfs.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_BuscaCep.setIcon(icon3)
        self.bt_BuscaCep.setIconSize(QtCore.QSize(30, 30))
        self.bt_BuscaCep.setObjectName("bt_BuscaCep")
        self.bt_BuscaCep_2 = QtWidgets.QPushButton(parent=self.fr_FormClientes)
        self.bt_BuscaCep_2.setGeometry(QtCore.QRect(120, 360, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bt_BuscaCep_2.setFont(font)
        self.bt_BuscaCep_2.setStyleSheet("QPushButton{\n"
"background: #7AB32E;\n"
"color: #FFF\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_BuscaCep_2.setText("")
        self.bt_BuscaCep_2.setObjectName("bt_BuscaCep_2")
        self.tx_Credito = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Credito.setGeometry(QtCore.QRect(445, 150, 201, 25))
        self.tx_Credito.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Credito.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Credito.setPlaceholderText("")
        self.tx_Credito.setObjectName("tx_Credito")
        self.lb_FormProdutos_25 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_25.setGeometry(QtCore.QRect(450, 120, 190, 20))
        self.lb_FormProdutos_25.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_25.setObjectName("lb_FormProdutos_25")

        self.retranslateUi(Form_Cad_Clientes)
        QtCore.QMetaObject.connectSlotsByName(Form_Cad_Clientes)
        Form_Cad_Clientes.setTabOrder(self.tx_Id, self.tx_Nome)
        Form_Cad_Clientes.setTabOrder(self.tx_Nome, self.tx_cpf)
        Form_Cad_Clientes.setTabOrder(self.tx_cpf, self.tx_rg)
        Form_Cad_Clientes.setTabOrder(self.tx_rg, self.tx_Telefone)
        Form_Cad_Clientes.setTabOrder(self.tx_Telefone, self.tx_Email)
        Form_Cad_Clientes.setTabOrder(self.tx_Email, self.tx_Cep)
        Form_Cad_Clientes.setTabOrder(self.tx_Cep, self.bt_BuscaCep)
        Form_Cad_Clientes.setTabOrder(self.bt_BuscaCep, self.tx_Endereco)
        Form_Cad_Clientes.setTabOrder(self.tx_Endereco, self.tx_Numero)
        Form_Cad_Clientes.setTabOrder(self.tx_Numero, self.tx_Bairro)
        Form_Cad_Clientes.setTabOrder(self.tx_Bairro, self.tx_Cidade)
        Form_Cad_Clientes.setTabOrder(self.tx_Cidade, self.tx_Estado)

    def retranslateUi(self, Form_Cad_Clientes):
        _translate = QtCore.QCoreApplication.translate
        Form_Cad_Clientes.setWindowTitle(_translate("Form_Cad_Clientes", "LC INFORMÁTICA| CADASTRO CLIENTE"))
        self.lb_FormProdutos.setText(_translate("Form_Cad_Clientes", "FICHA CADASTRAL CLIENTE"))
        self.lb_FormProdutos_2.setText(_translate("Form_Cad_Clientes", "NOME"))
        self.tx_Nome.setPlaceholderText(_translate("Form_Cad_Clientes", "NOME COMPLETO"))
        self.lb_FormProdutos_3.setText(_translate("Form_Cad_Clientes", "CPF"))
        self.lb_FormProdutos_4.setText(_translate("Form_Cad_Clientes", "RG"))
        self.tx_rg.setInputMask(_translate("Form_Cad_Clientes", "00.000.000-0"))
        self.tx_rg.setText(_translate("Form_Cad_Clientes", "..-"))
        self.lb_FormProdutos_8.setText(_translate("Form_Cad_Clientes", "ENDEREÇO"))
        self.tx_Cep.setInputMask(_translate("Form_Cad_Clientes", "99999-999"))
        self.tx_Cep.setPlaceholderText(_translate("Form_Cad_Clientes", "123456789"))
        self.lb_FormProdutos_10.setText(_translate("Form_Cad_Clientes", "CEP"))
        self.Bt_Voltar.setText(_translate("Form_Cad_Clientes", "CANCELAR"))
        self.Bt_Salvar.setText(_translate("Form_Cad_Clientes", "SALVAR"))
        self.tx_cpf.setInputMask(_translate("Form_Cad_Clientes", "000.000.000-00"))
        self.tx_cpf.setText(_translate("Form_Cad_Clientes", "..-"))
        self.lb_FormProdutos_23.setText(_translate("Form_Cad_Clientes", "Email"))
        self.lb_FormProdutos_24.setText(_translate("Form_Cad_Clientes", "TELEFONE"))
        self.tx_Telefone.setInputMask(_translate("Form_Cad_Clientes", "(00) 0000-00000"))
        self.tx_Telefone.setText(_translate("Form_Cad_Clientes", "() -"))
        self.lb_FormProdutos_11.setText(_translate("Form_Cad_Clientes", "ENDEREÇO"))
        self.lb_FormProdutos_12.setText(_translate("Form_Cad_Clientes", "Nº"))
        self.lb_FormProdutos_13.setText(_translate("Form_Cad_Clientes", "BAIRRO"))
        self.lb_FormProdutos_14.setText(_translate("Form_Cad_Clientes", "CIDADE"))
        self.lb_FormProdutos_15.setText(_translate("Form_Cad_Clientes", "ESTADO"))
        self.lb_FormProdutos_25.setText(_translate("Form_Cad_Clientes", "CRÉDITO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_Cad_Clientes = QtWidgets.QFrame()
    ui = Ui_Form_Cad_Clientes()
    ui.setupUi(Form_Cad_Clientes)
    Form_Cad_Clientes.show()
    sys.exit(app.exec())
