# Form implementation generated from reading ui file 'Form_Edit_Clientes.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_Edit_Clientes(object):
    def setupUi(self, Form_Edit_Clientes):
        Form_Edit_Clientes.setObjectName("Form_Edit_Clientes")
        Form_Edit_Clientes.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Form_Edit_Clientes.resize(675, 500)
        Form_Edit_Clientes.setMinimumSize(QtCore.QSize(675, 500))
        Form_Edit_Clientes.setMaximumSize(QtCore.QSize(675, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../img/edit.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form_Edit_Clientes.setWindowIcon(icon)
        self.fr_FormClientes = QtWidgets.QFrame(parent=Form_Edit_Clientes)
        self.fr_FormClientes.setGeometry(QtCore.QRect(0, 0, 1000, 500))
        self.fr_FormClientes.setStyleSheet("background: #FFF;\n"
"border: none")
        self.fr_FormClientes.setObjectName("fr_FormClientes")
        self.lb_FormProdutos = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos.setGeometry(QtCore.QRect(90, 10, 561, 30))
        self.lb_FormProdutos.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"\n"
"border-bottom: 2px solid #A2A2A2\n"
"}")
        self.lb_FormProdutos.setObjectName("lb_FormProdutos")
        self.lb_FormProdutos_2 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_2.setGeometry(QtCore.QRect(20, 60, 150, 20))
        self.lb_FormProdutos_2.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_2.setObjectName("lb_FormProdutos_2")
        self.tx_Nome = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Nome.setGeometry(QtCore.QRect(20, 85, 631, 25))
        self.tx_Nome.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Nome.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Nome.setObjectName("tx_Nome")
        self.lb_FormProdutos_3 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_3.setGeometry(QtCore.QRect(20, 130, 190, 20))
        self.lb_FormProdutos_3.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_3.setObjectName("lb_FormProdutos_3")
        self.lb_FormProdutos_4 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_4.setGeometry(QtCore.QRect(236, 130, 190, 20))
        self.lb_FormProdutos_4.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_4.setObjectName("lb_FormProdutos_4")
        self.tx_Rg = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Rg.setGeometry(QtCore.QRect(236, 160, 196, 25))
        self.tx_Rg.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Rg.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Rg.setInputMask("")
        self.tx_Rg.setText("")
        self.tx_Rg.setCursorPosition(0)
        self.tx_Rg.setPlaceholderText("")
        self.tx_Rg.setClearButtonEnabled(True)
        self.tx_Rg.setObjectName("tx_Rg")
        self.lb_FormProdutos_8 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_8.setGeometry(QtCore.QRect(20, 290, 630, 30))
        self.lb_FormProdutos_8.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: normal;\n"
"\n"
"border-bottom: 2px solid #A2A2A2;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_8.setObjectName("lb_FormProdutos_8")
        self.tx_Cep = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Cep.setGeometry(QtCore.QRect(20, 360, 100, 25))
        self.tx_Cep.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Cep.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Cep.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tx_Cep.setObjectName("tx_Cep")
        self.lb_FormProdutos_10 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_10.setGeometry(QtCore.QRect(20, 335, 50, 20))
        self.lb_FormProdutos_10.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_10.setObjectName("lb_FormProdutos_10")
        self.fr_BotoesFormProdutos = QtWidgets.QFrame(parent=self.fr_FormClientes)
        self.fr_BotoesFormProdutos.setGeometry(QtCore.QRect(0, 470, 1000, 30))
        self.fr_BotoesFormProdutos.setStyleSheet("background:#E1DFE0;\n"
"border: none;")
        self.fr_BotoesFormProdutos.setObjectName("fr_BotoesFormProdutos")
        self.bt_Salvar = QtWidgets.QPushButton(parent=self.fr_BotoesFormProdutos)
        self.bt_Salvar.setGeometry(QtCore.QRect(400, 0, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_Salvar.setFont(font)
        self.bt_Salvar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_Salvar.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.bt_Salvar.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.bt_Salvar.setStyleSheet("QPushButton {\n"
"background-color: #40a286;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #7AB32E;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/salvar/salvar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_Salvar.setIcon(icon1)
        self.bt_Salvar.setIconSize(QtCore.QSize(50, 25))
        self.bt_Salvar.setObjectName("bt_Salvar")
        self.bt_Voltar = QtWidgets.QPushButton(parent=self.fr_BotoesFormProdutos)
        self.bt_Voltar.setGeometry(QtCore.QRect(540, 0, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_Voltar.setFont(font)
        self.bt_Voltar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.bt_Voltar.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.bt_Voltar.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.bt_Voltar.setStyleSheet("QPushButton {\n"
"background-color: rgb(193, 0, 0);\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 85, 0);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/sair/delete_delete_exit_1577.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bt_Voltar.setIcon(icon2)
        self.bt_Voltar.setIconSize(QtCore.QSize(75, 25))
        self.bt_Voltar.setObjectName("bt_Voltar")
        self.tx_Cpf = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Cpf.setGeometry(QtCore.QRect(20, 160, 196, 25))
        self.tx_Cpf.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Cpf.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Cpf.setPlaceholderText("")
        self.tx_Cpf.setObjectName("tx_Cpf")
        self.lb_FormProdutos_23 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_23.setGeometry(QtCore.QRect(370, 220, 190, 20))
        self.lb_FormProdutos_23.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_23.setObjectName("lb_FormProdutos_23")
        self.lb_FormProdutos_24 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_24.setGeometry(QtCore.QRect(20, 220, 190, 20))
        self.lb_FormProdutos_24.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_24.setObjectName("lb_FormProdutos_24")
        self.tx_Email = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Email.setGeometry(QtCore.QRect(330, 250, 321, 25))
        self.tx_Email.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Email.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Email.setPlaceholderText("")
        self.tx_Email.setObjectName("tx_Email")
        self.tx_Telefone = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Telefone.setGeometry(QtCore.QRect(20, 250, 291, 25))
        self.tx_Telefone.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Telefone.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Telefone.setPlaceholderText("")
        self.tx_Telefone.setObjectName("tx_Telefone")
        self.lb_FormProdutos_11 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_11.setGeometry(QtCore.QRect(160, 335, 250, 20))
        self.lb_FormProdutos_11.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_11.setObjectName("lb_FormProdutos_11")
        self.tx_Endereco = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Endereco.setGeometry(QtCore.QRect(169, 360, 391, 25))
        self.tx_Endereco.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Endereco.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Endereco.setInputMask("")
        self.tx_Endereco.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_Endereco.setPlaceholderText("")
        self.tx_Endereco.setObjectName("tx_Endereco")
        self.lb_FormProdutos_12 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_12.setGeometry(QtCore.QRect(580, 335, 50, 20))
        self.lb_FormProdutos_12.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_12.setObjectName("lb_FormProdutos_12")
        self.tx_Numero = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Numero.setGeometry(QtCore.QRect(580, 360, 70, 25))
        self.tx_Numero.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Numero.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Numero.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.tx_Numero.setInputMask("")
        self.tx_Numero.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_Numero.setPlaceholderText("")
        self.tx_Numero.setObjectName("tx_Numero")
        self.tx_Bairro = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Bairro.setGeometry(QtCore.QRect(20, 415, 260, 25))
        self.tx_Bairro.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Bairro.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Bairro.setInputMask("")
        self.tx_Bairro.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_Bairro.setPlaceholderText("")
        self.tx_Bairro.setObjectName("tx_Bairro")
        self.lb_FormProdutos_13 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_13.setGeometry(QtCore.QRect(20, 390, 120, 20))
        self.lb_FormProdutos_13.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_13.setObjectName("lb_FormProdutos_13")
        self.tx_Cidade = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Cidade.setGeometry(QtCore.QRect(300, 415, 260, 25))
        self.tx_Cidade.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Cidade.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Cidade.setInputMask("")
        self.tx_Cidade.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_Cidade.setPlaceholderText("")
        self.tx_Cidade.setObjectName("tx_Cidade")
        self.lb_FormProdutos_14 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_14.setGeometry(QtCore.QRect(300, 390, 120, 20))
        self.lb_FormProdutos_14.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_14.setObjectName("lb_FormProdutos_14")
        self.lb_FormProdutos_15 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_15.setGeometry(QtCore.QRect(580, 390, 70, 20))
        self.lb_FormProdutos_15.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_15.setObjectName("lb_FormProdutos_15")
        self.tx_Estado = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Estado.setGeometry(QtCore.QRect(580, 415, 70, 25))
        self.tx_Estado.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Estado.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Estado.setInputMask("")
        self.tx_Estado.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tx_Estado.setPlaceholderText("")
        self.tx_Estado.setObjectName("tx_Estado")
        self.tx_Credito = QtWidgets.QLineEdit(parent=self.fr_FormClientes)
        self.tx_Credito.setGeometry(QtCore.QRect(450, 160, 201, 25))
        self.tx_Credito.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Credito.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Credito.setInputMask("")
        self.tx_Credito.setText("")
        self.tx_Credito.setCursorPosition(0)
        self.tx_Credito.setDragEnabled(False)
        self.tx_Credito.setReadOnly(False)
        self.tx_Credito.setObjectName("tx_Credito")
        self.lb_FormProdutos_25 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.lb_FormProdutos_25.setGeometry(QtCore.QRect(450, 130, 190, 20))
        self.lb_FormProdutos_25.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_25.setObjectName("lb_FormProdutos_25")
        self.label = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.label.setGeometry(QtCore.QRect(120, 360, 31, 25))
        self.label.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.fr_FormClientes)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 51, 31))
        self.label_2.setStyleSheet("background: #CFCFCF;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form_Edit_Clientes)
        QtCore.QMetaObject.connectSlotsByName(Form_Edit_Clientes)
        Form_Edit_Clientes.setTabOrder(self.tx_Nome, self.tx_Cpf)
        Form_Edit_Clientes.setTabOrder(self.tx_Cpf, self.tx_Rg)
        Form_Edit_Clientes.setTabOrder(self.tx_Rg, self.tx_Credito)
        Form_Edit_Clientes.setTabOrder(self.tx_Credito, self.tx_Telefone)
        Form_Edit_Clientes.setTabOrder(self.tx_Telefone, self.tx_Email)
        Form_Edit_Clientes.setTabOrder(self.tx_Email, self.tx_Cep)
        Form_Edit_Clientes.setTabOrder(self.tx_Cep, self.tx_Endereco)
        Form_Edit_Clientes.setTabOrder(self.tx_Endereco, self.tx_Numero)
        Form_Edit_Clientes.setTabOrder(self.tx_Numero, self.tx_Bairro)
        Form_Edit_Clientes.setTabOrder(self.tx_Bairro, self.tx_Cidade)
        Form_Edit_Clientes.setTabOrder(self.tx_Cidade, self.tx_Estado)

    def retranslateUi(self, Form_Edit_Clientes):
        _translate = QtCore.QCoreApplication.translate
        Form_Edit_Clientes.setWindowTitle(_translate("Form_Edit_Clientes", "LC INFORMÁTICA| EDITAR CLIENTE"))
        self.lb_FormProdutos.setText(_translate("Form_Edit_Clientes", "EDITAR CLIENTE"))
        self.lb_FormProdutos_2.setText(_translate("Form_Edit_Clientes", "NOME"))
        self.tx_Nome.setPlaceholderText(_translate("Form_Edit_Clientes", "NOME COMPLETO"))
        self.lb_FormProdutos_3.setText(_translate("Form_Edit_Clientes", "CPF"))
        self.lb_FormProdutos_4.setText(_translate("Form_Edit_Clientes", "RG"))
        self.lb_FormProdutos_8.setText(_translate("Form_Edit_Clientes", "ENDEREÇO"))
        self.tx_Cep.setInputMask(_translate("Form_Edit_Clientes", "99999-999"))
        self.tx_Cep.setPlaceholderText(_translate("Form_Edit_Clientes", "123456789"))
        self.lb_FormProdutos_10.setText(_translate("Form_Edit_Clientes", "CEP"))
        self.bt_Salvar.setText(_translate("Form_Edit_Clientes", "SALVAR"))
        self.bt_Voltar.setText(_translate("Form_Edit_Clientes", "CANCELAR"))
        self.tx_Cpf.setInputMask(_translate("Form_Edit_Clientes", "000.000.000-00"))
        self.tx_Cpf.setText(_translate("Form_Edit_Clientes", "..-"))
        self.lb_FormProdutos_23.setText(_translate("Form_Edit_Clientes", "Email"))
        self.lb_FormProdutos_24.setText(_translate("Form_Edit_Clientes", "TELEFONE"))
        self.tx_Telefone.setInputMask(_translate("Form_Edit_Clientes", "(00) 0000-0000"))
        self.lb_FormProdutos_11.setText(_translate("Form_Edit_Clientes", "ENDEREÇO"))
        self.lb_FormProdutos_12.setText(_translate("Form_Edit_Clientes", "Nº"))
        self.lb_FormProdutos_13.setText(_translate("Form_Edit_Clientes", "BAIRRO"))
        self.lb_FormProdutos_14.setText(_translate("Form_Edit_Clientes", "CIDADE"))
        self.lb_FormProdutos_15.setText(_translate("Form_Edit_Clientes", "ESTADO"))
        self.tx_Credito.setPlaceholderText(_translate("Form_Edit_Clientes", "DIGITE O VALOR SEM VIRGULAS"))
        self.lb_FormProdutos_25.setText(_translate("Form_Edit_Clientes", "CRÉDITO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_Edit_Clientes = QtWidgets.QFrame()
    ui = Ui_Form_Edit_Clientes()
    ui.setupUi(Form_Edit_Clientes)
    Form_Edit_Clientes.show()
    sys.exit(app.exec())
